Repository tektoncd/triggers, pull requests merged in 2019-09, with the labels that each got.

#93 Add deployments/finalizers to ClusterRole
  config/200-clusterrole.yaml
Labels: approved, lgtm, size/XS

#85 Handle Referenced Resource Naming within TriggerTemplates
  Gopkg.lock
  docs/triggertemplates.md
  examples/triggertemplates/triggertemplate.yaml
  pkg/template/event.go
  pkg/template/event_test.go
  pkg/template/resource.go
  pkg/template/resource_test.go
  test/eventlistener_test.go
Labels: approved, lgtm, size/L

#98 Add eventlisteners/finalizers to ClusterRole
  config/200-clusterrole.yaml
Labels: approved, lgtm, size/XS

#52 Issue38 test builders
  pkg/apis/triggers/v1alpha1/trigger_template_types.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  pkg/template/event_test.go
  test/builder/README.md
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
  test/builder/meta.go
  test/builder/meta_test.go
  test/builder/triggerbinding.go
  test/builder/triggerbinding_test.go
  test/builder/triggertemplate.go
  test/builder/triggertemplate_test.go
  test/eventlistener_test.go
Labels: approved, lgtm, size/XXL

#94 Tests for create-webhook task
  docs/create-webhook-run.yaml
  docs/create-webhook.yaml
  docs/createwebhook.md
  test/e2e-tests-ingress.sh
  test/e2e-tests.sh
  test/ingress/ingress-clusterrole.yaml
  test/ingress/ingress-clusterrolebinding.yaml
Labels: approved, lgtm, size/L

#104 Ignore spec.clusterIP when reconciling Service
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, lgtm, size/M

#90 Recover deployment and SVC if deleted by accident
  pkg/reconciler/v1alpha1/eventlistener/controller.go
  test/controller.go
Labels: approved, lgtm, size/S

#102 Default namespace for resource templates if not provided
  docs/README.md
  docs/eventlisteners.md
  docs/triggerbindings.md
  docs/triggertemplates.md
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  pkg/template/event_test.go
  test/eventlistener_test.go
Labels: approved, lgtm, size/L

#118 Move validate from example to validate-event.md
  docs/eventlisteners.md
  docs/validate-event.md
  examples/eventlisteners/eventlistener.yaml
Labels: approved, lgtm, size/M

#119 fix validation task error
  docs/validate-github-event.yaml
Labels: approved, lgtm, size/XS

#99 Set github webhook secret
  docs/create-webhook.yaml
  docs/createwebhook.md
Labels: approved, lgtm, size/M

#116 Use clusterIP as the default service type
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, lgtm, size/XS

#121 Add Test to check that payload is sent to the kubernetes api
  pkg/sink/sink_test.go
Labels: approved, lgtm, size/M

#96 Add label for resources create by EventListener
  Gopkg.lock
  docs/triggertemplates.md
  pkg/apis/triggers/v1alpha1/register.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  test/eventlistener_test.go
  third_party/VENDOR-LICENSE
  vendor/github.com/tidwall/sjson/LICENSE
  vendor/github.com/tidwall/sjson/sjson.go
  vendor/github.com/tidwall/sjson/sjson_gae.go
  vendor/github.com/tidwall/sjson/sjson_ngae.go
Labels: approved, lgtm, size/XL

#122 Adds release tasks and pipeline for triggers
  tekton/README.md
  tekton/account.yaml
  tekton/koparse/koparse.py
  tekton/koparse/test_koparse.py
  tekton/koparse/test_release.yaml
  tekton/publish-run.yaml
  tekton/publish.yaml
  tekton/release-pipeline-run.yaml
  tekton/release-pipeline.yaml
  tekton/resources.yaml
Labels: approved, lgtm, size/XXL

#123 Move params into EventListener
  docs/create-webhook.yaml
  docs/eventlisteners.md
  docs/triggerbindings.md
  docs/triggertemplates.md
  examples/README.md
  examples/eventlisteners/eventlistener.yaml
  examples/example-pipeline.yaml
  examples/triggerbindings/triggerbinding.yaml
  examples/triggertemplates/triggertemplate.yaml
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/trigger_binding_types.go
  pkg/apis/triggers/v1alpha1/trigger_binding_validation.go
  pkg/apis/triggers/v1alpha1/trigger_binding_validation_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  pkg/template/event.go
  pkg/template/event_test.go
  pkg/template/resource.go
  pkg/template/resource_test.go
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
  test/builder/triggerbinding.go
  test/builder/triggerbinding_test.go
  test/eventlistener_test.go
Labels: approved, lgtm, size/XXL

#127 Pass params directly from EventListener to TriggerTemplate
  docs/eventlisteners.md
  docs/triggerbindings.md
  docs/triggertemplates.md
  examples/eventlisteners/eventlistener.yaml
  examples/triggerbindings/triggerbinding.yaml
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/trigger_binding_types.go
  pkg/apis/triggers/v1alpha1/trigger_binding_validation.go
  pkg/apis/triggers/v1alpha1/trigger_binding_validation_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  pkg/template/event.go
  pkg/template/event_test.go
  pkg/template/resource.go
  pkg/template/resource_test.go
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
  test/builder/triggerbinding.go
  test/builder/triggerbinding_test.go
  test/eventlistener_test.go
Labels: approved, lgtm, size/XL

#130 Update Trigger deployments to use apps/v1 API version
  config/controller.yaml
  config/webhook.yaml
Labels: approved, lgtm, size/S

#128 Add TriggerValidate from Event Listener to test builder
  pkg/sink/sink_test.go
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
Labels: approved, lgtm, size/L

#131 Add Validation for trigger source to Example
  docs/eventlisteners.md
  docs/validate-event.md
  examples/README.md
  examples/eventlisteners/eventlistener.yaml
  examples/role-resources/role.yaml
  examples/role-resources/secret.yaml
  examples/role-resources/serviceaccount.yaml
Labels: approved, lgtm, size/M

#134 Add name to EventlistenerSpec Trigger
  docs/eventlisteners.md
  examples/eventlisteners/eventlistener.yaml
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
Labels: approved, lgtm, size/S

#70 Add EventListenerStatus: conditions for deployment/service readiness …
  Gopkg.lock
  config/200-clusterrole.yaml
  docs/eventlisteners.md
  examples/eventlisteners/eventlistener.yaml
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_types_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
  test/builder/meta.go
  test/controller.go
  test/controller_test.go
  test/eventlistener_test.go
  test/init_test.go
  test/wait.go
Labels: approved, lgtm, size/XXL

#133 Add triggers-eventid label for all resources created for each event
  docs/triggertemplates.md
  pkg/apis/triggers/v1alpha1/register.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  test/eventlistener_test.go
Labels: approved, lgtm, size/M

#139 Move Sink Port to 8080 to support Knative
  docs/create-webhook.yaml
  examples/README.md
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  test/e2e-tests-ingress.sh
Labels: approved, lgtm, size/S
