Repository tektoncd/triggers, pull requests merged in 2019-12, with the labels that each got.

#245 update label on event-display Pod
  docs/getting-started/pipeline.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#246 Fix release pipeline.
  tekton/publish.yaml
  tekton/release-pipeline-run.yaml
  tekton/release-pipeline.yaml
Labels: approved, lgtm, size/M

#242 Migrate EventListeners with binding to bindings
  pkg/apis/triggers/v1alpha1/contexts.go
  pkg/apis/triggers/v1alpha1/event_listener_defaults.go
  pkg/apis/triggers/v1alpha1/event_listener_defaults_test.go
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/template/resource.go
  third_party/VENDOR-LICENSE
Labels: approved, lgtm, size/L

#250 Delete config maps
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  test/controller.go
  test/controller_test.go
Labels: approved, lgtm, ok-to-test, size/L

#256 Fix e2e ingress test sleep wait behavior
  test/e2e-tests-ingress.sh
Labels: approved, lgtm, size/S

#238 Use dynamic client for resource creation.
  Gopkg.lock
  cmd/eventlistenersink/main.go
  pkg/client/dynamic/clientset/clientset.go
  pkg/client/dynamic/clientset/errorclient.go
  pkg/client/dynamic/clientset/tekton/tekton.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  pkg/template/resource.go
  vendor/k8s.io/client-go/rest/fake/fake.go
Labels: approved, lgtm, size/XL

#264 Fix golint error strings.
  pkg/apis/triggers/v1alpha1/event_listener_types_test.go
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/client/dynamic/clientset/errorclient.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  pkg/template/resource_test.go
Labels: approved, lgtm, size/M

#266 Fix v0.1.0 release link in main README
  README.md
Labels: approved, lgtm, size/XS

#268 Fetch resource metadata from unstructured
  Gopkg.lock
  pkg/sink/sink.go
  third_party/VENDOR-LICENSE
Labels: approved, lgtm, size/XL

#267 Remove namespace config.
  config/100-namespace.yaml
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#275 Temporarily disable markdown link check
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#274 Refactor functions to not be members of Sink 🚰
  pkg/resources/create.go
  pkg/resources/create_test.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  test/resources.go
Labels: approved, lgtm, size/XL

#273 fix typo
  docs/eventlisteners.md
  docs/getting-started/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#277 Fix incorrect URLs
  docs/eventlisteners.md
  docs/install.md
Labels: approved, lgtm, size/XS

#278 Fix serviceAccountName in triggers.yaml
  docs/getting-started/triggers.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#282 Fix serviceAccountName in triggers.yaml
  docs/getting-started/triggers.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#284 Add triggerbinding and triggertemplate to test controller
  test/controller.go
  test/controller_test.go
Labels: approved, lgtm, size/L

#286 Fix spelling errors
  pkg/interceptors/webhook/interceptors.go
  test/resources.go
Labels: approved, lgtm, ok-to-test, size/XS

#261 Change sink response to return JSON
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  test/eventlistener_test.go
Labels: approved, lgtm, size/M

#280 Set labels directly on Unstructured
  Gopkg.lock
  pkg/apis/triggers/v1alpha1/register.go
  pkg/resources/create.go
  pkg/resources/create_test.go
  pkg/sink/sink.go
  third_party/VENDOR-LICENSE
  vendor/github.com/tidwall/gjson/LICENSE
  vendor/github.com/tidwall/gjson/gjson.go
  vendor/github.com/tidwall/gjson/gjson_gae.go
  vendor/github.com/tidwall/gjson/gjson_ngae.go
  vendor/github.com/tidwall/match/LICENSE
  vendor/github.com/tidwall/match/match.go
  vendor/github.com/tidwall/pretty/LICENSE
  vendor/github.com/tidwall/pretty/pretty.go
  vendor/github.com/tidwall/sjson/LICENSE
  vendor/github.com/tidwall/sjson/sjson.go
  vendor/github.com/tidwall/sjson/sjson_gae.go
  vendor/github.com/tidwall/sjson/sjson_ngae.go
Labels: approved, lgtm, size/XXL

#279 Preserve escaped characters when parsing json path 🦟
  pkg/resources/create.go
  pkg/resources/create_test.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  pkg/template/event_test.go
  pkg/template/jsonpath.go
  pkg/template/jsonpath_test.go
  pkg/template/resource_test.go
  test/eventlistener_test.go
  test/params.go
  test/testdata/pr.json
Labels: approved, lgtm, size/L

#292 Correctly capitalize GitLab (not "Gitlab")
  docs/eventlisteners.md
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/interceptors/gitlab/gitlab.go
  pkg/interceptors/gitlab/gitlab_test.go
  pkg/sink/sink.go
Labels: approved, lgtm, size/M

#291 Correctly capitalize "GitHub" (not "Github")
  docs/eventlisteners.md
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/interceptors/github/github.go
  pkg/interceptors/github/github_test.go
  pkg/sink/sink.go
Labels: approved, lgtm, size/M

#297 Fix example README - Change listener to el-listener
  examples/README.md
Labels: approved, lgtm, size/XS

#294 Fix ingress-run, change serviceAccount to serviceAccountName
  docs/getting-started/ingress-run.yaml
Labels: approved, lgtm, size/XS
