Repository tektoncd/triggers, pull requests merged in 2019-08, with the labels that each got.

#51 Implement TriggerResourceTemplate Spec as []byte blob
  docs/triggertemplates.md
  pkg/apis/triggers/v1alpha1/trigger_template_types.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#58 Correct the format of variable interpolation from ${} to $()
  docs/triggerbindings.md
  docs/triggertemplates.md
Labels: approved, lgtm, size/S

#60 Update EventListener deployment. Set up EventListener pod trigger cli…
  cmd/eventlistener/main.go
  docs/eventlisteners.md
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
Labels: approved, lgtm, size/M

#66 Revert "Use examples as part of documentation. Add utility/test to keep docs …"
  DEVELOPMENT.md
  docs/eventlisteners.md
  docs/package.json
  docs/triggerbindings.md
  docs/triggertemplates.md
  examples/eventlisteners/eventlistener.yaml
  examples/triggerbindings/triggerbinding.yaml
  examples/triggertemplates/triggertemplate.yaml
  hack/update-docs.sh
  test/e2e-tests-yaml.sh
  test/e2e-tests.sh
  test/presubmit-tests.sh
Labels: approved, lgtm, size/L

#72 Remove duplicate example
  docs/triggerbindings.md
Labels: approved, lgtm, size/S

#63 Issue55 reusable bindings
  README.md
  cmd/eventlistener/main.go
  docs/eventlisteners.md
  docs/triggerbindings.md
  examples/eventlisteners/eventlistener.yaml
  examples/triggerbindings/triggerbinding.yaml
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/trigger_binding_defaults.go
  pkg/apis/triggers/v1alpha1/trigger_binding_types.go
  pkg/apis/triggers/v1alpha1/trigger_binding_validation.go
  pkg/apis/triggers/v1alpha1/trigger_template_defaults.go
  pkg/apis/triggers/v1alpha1/trigger_template_types.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  test/eventlistener_test.go
Labels: approved, lgtm, size/L

#74 Create resource(s) from an event
  Gopkg.lock
  cmd/eventlistener/main.go
  cmd/eventlistenersink/README.md
  cmd/eventlistenersink/kodata/LICENSE
  cmd/eventlistenersink/kodata/VENDOR-LICENSE
  cmd/eventlistenersink/main.go
  config/controller.yaml
  docs/triggerbindings.md
  docs/triggertemplates.md
  examples/triggerbindings/triggerbinding.yaml
  examples/triggertemplates/triggertemplate.yaml
  pkg/apis/triggers/v1alpha1/trigger_template_types.go
  pkg/parse/json/examples/github/pullrequest.json
  pkg/parse/json/json.go
  pkg/parse/json/json_test.go
  pkg/parse/validate.go
  pkg/parse/validate_test.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  pkg/sink/initialization.go
  pkg/sink/initialization_test.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  pkg/template/event.go
  pkg/template/event_test.go
  pkg/template/examples/digger.json
  pkg/template/examples/github-push.json
  pkg/template/resource.go
  pkg/template/resource_test.go
  test/eventlistener_test.go
  test/init_test.go
  test/logs.go
  test/presubmit-tests.sh
  test/wait.go
  third_party/VENDOR-LICENSE
  vendor/k8s.io/client-go/rest/fake/fake.go
Labels: approved, lgtm, size/XXL

#82 Adding create-webhook tekton task
  docs/create-webhook-run.yaml
  docs/create-webhook.yaml
  docs/createwebhook.md
Labels: approved, lgtm, size/L
