Repository tektoncd/triggers, pull requests merged in 2019-10, with the labels that each got.

#138 Make EventListener an Addressable
  Gopkg.lock
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_types_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
Labels: approved, lgtm, size/XL

#129 Owners
  OWNERS
Labels: approved, lgtm, size/XS

#100 Update WebhookTask
  docs/README.md
  docs/create-ingress.yaml
  docs/create-webhook-run.yaml
  docs/create-webhook.yaml
  docs/createwebhook.md
  docs/eventlisteners.md
  docs/triggerbindings.md
  docs/triggertemplates.md
  examples/eventlisteners/eventlistener.yaml
  examples/role-resources/binding.yaml
  examples/triggerbindings/triggerbinding.yaml
  examples/triggertemplates/triggertemplate.yaml
  test/e2e-tests-ingress.sh
  test/e2e-tests-yaml.sh
  test/ingress/100-ingress-clusterrole.yaml
  test/ingress/200-ingress-clusterrolebinding.yaml
Labels: approved, lgtm, size/XXL

#141 Update TriggerTemplate documentation to specify restriction to create…
  docs/triggertemplates.md
  pkg/apis/triggers/v1alpha1/trigger_template_types.go
Labels: approved, lgtm, size/S

#147 Add unique label for the generated service and deployment
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  test/eventlistener_test.go
Labels: approved, lgtm, size/L

#151 Update EventListener generated resource names
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  test/eventlistener_test.go
Labels: approved, lgtm, size/S

#154 Fix release task by copying input bucket contents
  tekton/publish.yaml
Labels: approved, lgtm, size/S

#156 Fix typo in eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
Labels: approved, lgtm, ok-to-test, size/XS

#162 Add simple cron trigger example.
  examples/cron/README.md
  examples/cron/binding.yaml
  examples/cron/cronjob.yaml
  examples/cron/eventlistener.yaml
  examples/cron/example-pipeline.yaml
  examples/cron/role.yaml
  examples/cron/secret.yaml
  examples/cron/serviceaccount.yaml
  examples/cron/triggerbinding.yaml
  examples/cron/triggertemplate.yaml
Labels: approved, lgtm, size/M

#163 Add interceptor headers to optionally pass trigger specific information
  docs/eventlisteners.md
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
  test/e2e-tests-yaml.sh
Labels: approved, lgtm, size/L

#168 Fix EventListener prefix to be "-" instead of "--"
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
Labels: approved, lgtm, size/XS

#171 Update README to remove WIP warning
  README.md
Labels: approved, lgtm, size/XS

#172 Fix interceptor headers to be a deepcopy
  pkg/sink/interceptors.go
  pkg/sink/sink_test.go
Labels: approved, lgtm, size/S

#166 Make TriggerBinding optional in EventListener.
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/template/resource.go
  pkg/template/resource_test.go
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
Labels: approved, lgtm, size/M

#167 Ignore EventListener service NodePort on reconcile
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, lgtm, ok-to-test, size/S

#173 Fix linting and formatting errors.
  cmd/eventlistenersink/main.go
  pkg/apis/triggers/v1alpha1/event_listener_defaults.go
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_types_test.go
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/register.go
  pkg/apis/triggers/v1alpha1/trigger_binding_types.go
  pkg/apis/triggers/v1alpha1/trigger_binding_validation.go
  pkg/apis/triggers/v1alpha1/trigger_template_types.go
  pkg/apis/triggers/v1alpha1/trigger_template_validation.go
  pkg/reconciler/v1alpha1/eventlistener/controller.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/sink/initialization.go
  pkg/sink/initialization_test.go
  pkg/sink/interceptors.go
  pkg/sink/interceptors_test.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  pkg/template/event.go
  pkg/template/resource.go
  pkg/template/resource_test.go
Labels: approved, lgtm, size/L

#160 Validate EventListener references
  Gopkg.lock
  Gopkg.toml
  cmd/webhook/main.go
  docs/eventlisteners.md
  examples/eventlisteners/eventlistener-interceptor.yaml
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/trigger_template_validation.go
  test/builder/eventlistener.go
  test/e2e-tests-ingress.sh
  test/eventlistener_test.go
  test/ingress/100-ingress-clusterrole.yaml
  vendor/k8s.io/client-go/discovery/cached_discovery.go
  vendor/k8s.io/client-go/discovery/round_tripper.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/k8s.io/client-go/kubernetes/typed/policy/v1beta1/fake/fake_eviction_expansion.go
  vendor/k8s.io/client-go/pkg/apis/clientauthentication/doc.go
  vendor/k8s.io/client-go/pkg/apis/clientauthentication/v1alpha1/doc.go
  vendor/k8s.io/client-go/pkg/apis/clientauthentication/v1beta1/doc.go
  vendor/k8s.io/client-go/pkg/version/doc.go
  vendor/k8s.io/client-go/rest/config.go
  vendor/k8s.io/client-go/rest/token_source.go
  vendor/k8s.io/client-go/rest/transport.go
  vendor/k8s.io/client-go/tools/cache/heap.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/api/doc.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/doc.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/transport/config.go
  vendor/k8s.io/client-go/transport/round_trippers.go
  vendor/k8s.io/client-go/util/workqueue/rate_limitting_queue.go
Labels: approved, lgtm, size/XL

#152 Document exposing EL with nginx ingress
  docs/eventlisteners.md
  docs/exposing-eventlisteners.md
  docs/getting-started/README.md
Labels: approved, lgtm, size/M

#175 Introduce EventListener.Spec.ServiceType
  docs/eventlisteners.md
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, lgtm, ok-to-test, size/M

#177 Fix release task with pipeline 0.7 syntax
  tekton/publish.yaml
Labels: approved, lgtm, size/S

#179 Update documentation:
  docs/eventlisteners.md
  docs/triggerbindings.md
Labels: approved, lgtm, size/M

#181 Add docs for installing Tekton Triggers
  README.md
  docs/getting-started/README.md
  docs/install.md
Labels: approved, lgtm, size/M

#183 Support more JSON array query syntax for the body
  docs/triggerbindings.md
  pkg/template/event.go
  pkg/template/event_test.go
Labels: approved, lgtm, size/S

#190 Update cron example with new EventListener prefix.
  examples/cron/cronjob.yaml
Labels: approved, lgtm, size/XS

#197 add log entry for each generated resource
  pkg/sink/sink.go
Labels: approved, lgtm, size/XS
