Repository tektoncd/triggers, pull requests merged in 2019-11, with the labels that each got.

#198 Eventlistener response code change
  pkg/sink/sink.go
  pkg/sink/sink_test.go
Labels: approved, lgtm, size/S

#191 Allow multiple bindings in triggers.
  docs/eventlisteners.md
  docs/getting-started/triggers.yaml
  docs/triggerbindings.md
  examples/cron/eventlistener.yaml
  examples/eventlisteners/eventlistener-interceptor.yaml
  examples/eventlisteners/eventlistener.yaml
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/template/event.go
  pkg/template/event_test.go
  pkg/template/resource.go
  pkg/template/resource_test.go
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
  test/e2e-tests-ingress.sh
Labels: approved, lgtm, size/L

#206 Fix code block formatting
  docs/triggerbindings.md
Labels: approved, lgtm, size/S

#204 add logging library to EventListener
  Gopkg.lock
  cmd/eventlistenersink/main.go
  cmd/webhook/main.go
  config/config-logging.yaml
  docs/eventlisteners.md
  examples/role-resources/role.yaml
  pkg/logging/logging.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  test/eventlistener_test.go
  vendor/github.com/tektoncd/pipeline/pkg/logging/config.go
Labels: approved, lgtm, size/L

#193 Update EventListener Addressable to include port
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
Labels: approved, lgtm, ok-to-test, size/M

#208 Set a timeout for requests to interceptor services
  cmd/eventlistenersink/main.go
  pkg/sink/interceptors.go
  pkg/sink/interceptors_test.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
Labels: approved, lgtm, size/M

#210 Fix triggerbindings.md 'binding' to 'bindings'
  docs/triggerbindings.md
Labels: approved, lgtm, size/S

#214 Add impossible to see missing "h"
  docs/getting-started/README.md
Labels: approved, lgtm, size/XS

#215 Add configmap permissions to getting started RBAC
  docs/getting-started/rbac/admin-role.yaml
Labels: approved, lgtm, size/XS

#211 Rename sink.Resource to sink.Sink
  cmd/eventlistenersink/main.go
  pkg/apis/triggers/v1alpha1/event_listener_types_test.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/trigger_binding_validation_test.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  pkg/sink/initialization_test.go
  pkg/sink/interceptors.go
  pkg/sink/interceptors_test.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
Labels: approved, lgtm, size/XXL

#212 Remove Params from EventListener
  docs/eventlisteners.md
  examples/cron/eventlistener.yaml
  examples/eventlisteners/eventlistener-interceptor.yaml
  examples/eventlisteners/eventlistener.yaml
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  pkg/template/event.go
  pkg/template/event_test.go
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
  test/e2e-tests-ingress.sh
  test/eventlistener_test.go
Labels: approved, lgtm, size/L

#219 Add links to versioned docs in README.md
  README.md
Labels: approved, lgtm, size/XS

#220 Update GitHub webhook task webhookevents param
  docs/create-webhook.yaml
Labels: approved, lgtm, size/XS

#216 Core interceptor refactor.
  docs/eventlisteners.md
  examples/eventlisteners/eventlistener-interceptor.yaml
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/interceptors/interceptors.go
  pkg/interceptors/webhook/interceptors.go
  pkg/interceptors/webhook/interceptors_test.go
  pkg/interceptors/webhook/sink.go
  pkg/interceptors/webhook/sink_test.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XL

#213 Automatically label generated resources with trigger name.
  docs/eventlisteners.md
  pkg/apis/triggers/v1alpha1/register.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  test/eventlistener_test.go
Labels: approved, lgtm, size/L

#224 Add kube client oidc authentication support for testing
  Gopkg.lock
  test/init_test.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go
Labels: approved, lgtm, ok-to-test, size/L

#221 Add an initial Github interceptor.
  README.md
  cmd/eventlistenersink/main.go
  docs/eventlisteners.md
  docs/exposing-eventlisteners.md
  docs/getting-started/README.md
  examples/eventlisteners/github-eventlistener-interceptor.yaml
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/interceptors/github/github.go
  pkg/interceptors/github/github_test.go
  pkg/interceptors/interceptors.go
  pkg/interceptors/webhook/sink.go
  pkg/sink/sink.go
Labels: approved, lgtm, size/L

#225 Simplify merging params in Bindings
  pkg/template/event.go
  pkg/template/event_test.go
  pkg/template/resource.go
  pkg/template/resource_test.go
Labels: approved, lgtm, size/XXL

#226 Refactor template resolution into separate binding and template funcs.
  pkg/sink/sink.go
  pkg/template/event.go
  pkg/template/event_test.go
  pkg/template/resource.go
  pkg/template/resource_test.go
Labels: approved, lgtm, size/L

#232 Avoid using gjson to parse a json.RawMessage
  pkg/apis/triggers/v1alpha1/trigger_template_types.go
Labels: approved, lgtm, size/S

#228 Add support for Github event type filtering to the Github validator.
  docs/eventlisteners.md
  examples/eventlisteners/github-eventlistener-interceptor.yaml
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/interceptors/github/github.go
  pkg/interceptors/github/github_test.go
Labels: approved, lgtm, size/L

#236 Add app.kubernetes.io labels to controller and webhook 🏷
  config/controller.yaml
  config/webhook.yaml
Labels: approved, lgtm, size/XS

#235 Add event type filtering to the gitlab interceptor.
  docs/eventlisteners.md
  examples/eventlisteners/gitlab-eventlistener-interceptor.yaml
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/interceptors/gitlab/gitlab.go
  pkg/interceptors/gitlab/gitlab_test.go
  third_party/VENDOR-LICENSE
Labels: approved, lgtm, size/L

#240 Remove bodyPathDigger test
  pkg/template/event_test.go
  pkg/template/examples/digger.json
  pkg/template/examples/github-push.json
Labels: approved, lgtm, size/L
