Repository tektoncd/triggers, pull requests merged in 2019-07, with the labels that each got.

#20 Specify the purpose of the triggers repo in README
  README.md
Labels: approved, lgtm, size/S

#22 Add some more sections and details to our docs 📝
  README.md
Labels: approved, lgtm, size/S

#27 Add codegen for trigger_template_types
  pkg/apis/triggers/v1alpha1/trigger_template_types.go
  pkg/client/clientset/versioned/typed/triggers/v1alpha1/fake/fake_triggers_client.go
  pkg/client/clientset/versioned/typed/triggers/v1alpha1/fake/fake_triggertemplate.go
  pkg/client/clientset/versioned/typed/triggers/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/triggers/v1alpha1/triggers_client.go
  pkg/client/clientset/versioned/typed/triggers/v1alpha1/triggertemplate.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/triggers/v1alpha1/interface.go
  pkg/client/informers/externalversions/triggers/v1alpha1/triggertemplate.go
  pkg/client/listers/triggers/v1alpha1/expansion_generated.go
  pkg/client/listers/triggers/v1alpha1/triggertemplate.go
Labels: approved, lgtm, size/XL

#24 Adding type docs
  docs/README.md
  docs/eventlisteners.md
  docs/triggerbindings.md
  docs/triggertemplates.md
  images/TriggerFlow.png
Labels: approved, lgtm, size/L

#30 Remove outdated warning notes in the DEVELOPMENT doc
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS

#29 Append "triggers" to config-observability name
  config/config-observability.yaml
  config/controller.yaml
Labels: approved, lgtm, size/XS

#31 Remove unnecessary linter file exclusion
  .errcheck.txt
  .golangci.yml
Labels: approved, lgtm, size/XS

#41 Link README to the documentation
  README.md
Labels: approved, lgtm, size/S

#34 Handle arbitrary payloads
  Gopkg.lock
  docs/package.json
  pkg/parse/json/examples/digger/digger.json
  pkg/parse/json/examples/github/pullrequest.json
  pkg/parse/json/json.go
  pkg/parse/json/json_test.go
  pkg/parse/validate.go
  pkg/parse/validate_test.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/v1alpha1/eventlistener/controller.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  vendor/github.com/tidwall/gjson/LICENSE
  vendor/github.com/tidwall/gjson/gjson.go
  vendor/github.com/tidwall/gjson/gjson_gae.go
  vendor/github.com/tidwall/gjson/gjson_ngae.go
  vendor/github.com/tidwall/match/LICENSE
  vendor/github.com/tidwall/match/match.go
  vendor/github.com/tidwall/pretty/LICENSE
  vendor/github.com/tidwall/pretty/pretty.go
Labels: approved, lgtm, size/XXL
