Repository tektoncd/triggers, pull requests merged in 2020-09, with the labels that each got.

#730 Updates to the happy path readme(s)
  README.md
  docs/getting-started/README.md
Labels: approved, lgtm, size/S

#739 Remove vendor-specific cluster setup instructions
  docs/install.md
Labels: approved, lgtm, size/S

#740 ELTrigger Binding and Template type to TriggerSpec
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
Labels: approved, kind/misc, lgtm, size/S

#742 Update link to happy path
  docs/exposing-eventlisteners.md
Labels: approved, kind/documentation, lgtm, size/XS

#743 Update pull request template for release-note
  .github/pull_request_template.md
Labels: approved, area/release, lgtm, size/S

#745 Add basic syntactical parsing of CEL filters and expressions.
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
Labels: approved, lgtm, release-note, size/M

#733 Migrate to using generated reconcilers
  .golangci.yml
  cmd/controller/main.go
  config/200-clusterrole.yaml
  go.mod
  go.sum
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/client/injection/reconciler/triggers/v1alpha1/eventlistener/controller.go
  pkg/client/injection/reconciler/triggers/v1alpha1/eventlistener/reconciler.go
  pkg/client/injection/reconciler/triggers/v1alpha1/eventlistener/stub/controller.go
  pkg/client/injection/reconciler/triggers/v1alpha1/eventlistener/stub/reconciler.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/v1alpha1/eventlistener/controller.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  third_party/knative.dev/caching/pkg/LICENSE
  vendor/knative.dev/caching/LICENSE
  vendor/knative.dev/caching/pkg/apis/caching/register.go
  vendor/knative.dev/caching/pkg/apis/caching/v1alpha1/doc.go
  vendor/knative.dev/caching/pkg/apis/caching/v1alpha1/image_defaults.go
  vendor/knative.dev/caching/pkg/apis/caching/v1alpha1/image_types.go
  vendor/knative.dev/caching/pkg/apis/caching/v1alpha1/image_validation.go
  vendor/knative.dev/caching/pkg/apis/caching/v1alpha1/register.go
  vendor/knative.dev/caching/pkg/apis/caching/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/doc.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/scheme/doc.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/typed/caching/v1alpha1/caching_client.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/typed/caching/v1alpha1/doc.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/typed/caching/v1alpha1/generated_expansion.go
  vendor/knative.dev/caching/pkg/client/clientset/versioned/typed/caching/v1alpha1/image.go
  vendor/modules.txt
Labels: approved, kind/feature, kind/misc, lgtm, size/XXL

#721 Update eventlistener doc to include eventlistener responsibility
  docs/eventlisteners.md
Labels: approved, kind/documentation, lgtm, size/M

#749 Add release links to versioned docs for v0.8.0
  README.md
  tekton/release-cheat-sheet.md
Labels: approved, kind/documentation, lgtm, release-note, size/XS

#751 Handle validation, defaults and working behavior for Replicas
  docs/eventlisteners.md
  pkg/apis/triggers/v1alpha1/event_listener_defaults.go
  pkg/apis/triggers/v1alpha1/event_listener_defaults_test.go
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, lgtm, release-note, size/M

#755 Add a IdleTimeout for EL sink
  cmd/eventlistenersink/main.go
Labels: approved, lgtm, release-note, size/S

#753 Merge annotations before propagation
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, lgtm, release-note, size/M

#756 Add release links to versioned docs for v0.8.1
  README.md
Labels: approved, kind/documentation, lgtm, release-note, size/XS

#760 Refactor to not use logger from pipeline
  pkg/interceptors/bitbucket/bitbucket_test.go
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/github/github_test.go
  pkg/interceptors/gitlab/gitlab_test.go
  vendor/github.com/tektoncd/pipeline/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, kind/cleanup, lgtm, release-note-none, size/M

#757 Use refs instead of name to refer to Bindings
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/trigger_validation_test.go
  pkg/sink/sink_test.go
  test/eventlistener_scale_test.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/M

#763 Un-indent release not blocks in PR template
  .github/pull_request_template.md
Labels: approved, kind/misc, lgtm, release-note-none, size/S

#734 Enhance existing eventlistener to support PodTemplate for Deployment using duck type
  docs/eventlisteners.md
  examples/github/github-eventlistener-interceptor.yaml
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
  test/eventlistener_test.go
Labels: approved, kind/feature, lgtm, release-note, size/XL

#764 Cleanup exported methods which are used in the same package
  pkg/resources/create.go
  pkg/resources/create_test.go
  pkg/template/event.go
  pkg/template/jsonpath.go
  pkg/template/jsonpath_test.go
  pkg/template/resource.go
  pkg/template/resource_test.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/M

#766 cel-go with string upper and lower-casing.
  go.mod
  go.sum
  pkg/interceptors/cel/cel_test.go
  vendor/github.com/google/cel-go/cel/BUILD.bazel
  vendor/github.com/google/cel-go/cel/env.go
  vendor/github.com/google/cel-go/cel/options.go
  vendor/github.com/google/cel-go/cel/program.go
  vendor/github.com/google/cel-go/checker/BUILD.bazel
  vendor/github.com/google/cel-go/checker/checker.go
  vendor/github.com/google/cel-go/checker/env.go
  vendor/github.com/google/cel-go/common/containers/BUILD.bazel
  vendor/github.com/google/cel-go/common/containers/container.go
  vendor/github.com/google/cel-go/common/overloads/overloads.go
  vendor/github.com/google/cel-go/common/packages/BUILD.bazel
  vendor/github.com/google/cel-go/common/packages/packager.go
  vendor/github.com/google/cel-go/common/types/pb/type.go
  vendor/github.com/google/cel-go/ext/BUILD.bazel
  vendor/github.com/google/cel-go/ext/README.md
  vendor/github.com/google/cel-go/ext/encoders.go
  vendor/github.com/google/cel-go/ext/guards.go
  vendor/github.com/google/cel-go/ext/strings.go
  vendor/github.com/google/cel-go/interpreter/BUILD.bazel
  vendor/github.com/google/cel-go/interpreter/attribute_patterns.go
  vendor/github.com/google/cel-go/interpreter/attributes.go
  vendor/github.com/google/cel-go/interpreter/coster.go
  vendor/github.com/google/cel-go/interpreter/decorators.go
  vendor/github.com/google/cel-go/interpreter/interpretable.go
  vendor/github.com/google/cel-go/interpreter/interpreter.go
  vendor/github.com/google/cel-go/interpreter/planner.go
  vendor/github.com/google/cel-go/interpreter/prune.go
  vendor/github.com/google/cel-go/parser/parser.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/XXL

#769 Fix Binding builder to only use ref
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/sink/sink_test.go
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
  test/eventlistener_test.go
Labels: approved, kind/bug, lgtm, release-note-none, size/L

#770 Update README.md
  docs/getting-started/README.md
Labels: approved, lgtm, ok-to-test, release-note, size/XS

#780 Add the pod resource to the test controller
  test/controller.go
  test/controller_test.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/pod.go
  vendor/modules.txt
Labels: approved, kind/feature, kind/misc, lgtm, release-note-none, size/L
