Repository tektoncd/triggers, pull requests merged in 2020-10, with the labels that each got.

#785 Enhance validation code for triggers
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/trigger_binding_validation.go
  pkg/apis/triggers/v1alpha1/trigger_template_validation.go
  pkg/apis/triggers/v1alpha1/trigger_template_validation_test.go
  pkg/apis/triggers/v1alpha1/trigger_validation.go
Labels: approved, lgtm, release-note, size/L

#786 Update submitter checklist to have release notes block
  .github/pull_request_template.md
Labels: approved, lgtm, release-note-none, size/XS

#768 Adds support for name/value embedded Bindings
  cmd/binding-eval/cmd/root.go
  cmd/binding-eval/cmd/root_test.go
  cmd/triggerrun/cmd/root_test.go
  docs/eventlisteners.md
  docs/triggers.md
  examples/gitlab/gitlab-push-listener.yaml
  pkg/apis/triggers/v1alpha1/trigger_defaults.go
  pkg/apis/triggers/v1alpha1/trigger_defaults_test.go
  pkg/apis/triggers/v1alpha1/trigger_types.go
  pkg/apis/triggers/v1alpha1/trigger_validation.go
  pkg/apis/triggers/v1alpha1/trigger_validation_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/template/event.go
  pkg/template/event_test.go
  pkg/template/resource.go
  pkg/template/resource_test.go
Labels: approved, lgtm, release-note-action-required, size/XL

#790 Add Clusterrole Aggregate View and Edit for Trigger CRD
  config/clusterrole-aggregate-edit.yaml
  config/clusterrole-aggregate-view.yaml
Labels: approved, lgtm, release-note, size/XS

#789 Set runAsUser uid for nonroot distroless image
  config/controller.yaml
  config/webhook.yaml
Labels: approved, kind/bug, lgtm, release-note, size/XS

#761 apply triggertemplate param default value if body/header based triggerbinding param missing from body/header
  docs/triggerbindings.md
  docs/triggertemplates.md
  examples/README.md
  pkg/template/event.go
  pkg/template/event_test.go
  pkg/template/resource.go
  pkg/template/resource_test.go
Labels: approved, lgtm, release-note-none, size/L

#794 Remove explicit pinning of golang version 📌
  tekton/release-pipeline.yaml
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#783 Add support for embedded trigger templates
  docs/eventlisteners.md
  docs/triggers.md
  examples/gitlab/gitlab-push-listener.yaml
  pkg/apis/triggers/v1alpha1/trigger_types.go
  pkg/apis/triggers/v1alpha1/trigger_validation.go
  pkg/apis/triggers/v1alpha1/trigger_validation_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/template/resource.go
  pkg/template/resource_test.go
  test/raw.go
Labels: approved, kind/feature, lgtm, release-note, size/L

#798 Fix TestTrigger_Error using deterministic inputs
  cmd/triggerrun/cmd/root.go
  cmd/triggerrun/cmd/root_test.go
Labels: approved, kind/bug, lgtm, release-note, size/S

#804 Revert "dibyo's point about only EL sink/interceptors reading secrets"
  config/200-role.yaml
  config/201-rolebinding.yaml
  examples/role-resources/clustertriggerbinding-roles/clusterrole.yaml
Labels: approved, kind/bug, lgtm, release-note-none, size/S

#802 Add timestaps in logs
  config/config-logging.yaml
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
Labels: approved, kind/feature, lgtm, release-note, size/XS

#806 Improve the error message when URL form encoding is received.
  pkg/interceptors/github/github.go
  pkg/interceptors/github/github_test.go
Labels: approved, kind/feature, lgtm, release-note, size/S

#810 Don't log Fatal when handling events in the eventlistener
  go.mod
  go.sum
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/FAQ.md
  vendor/go.uber.org/zap/config.go
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/options.go
  vendor/go.uber.org/zap/sink.go
  vendor/go.uber.org/zap/stacktrace.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/encoder.go
  vendor/go.uber.org/zap/zapcore/entry.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/go.uber.org/zap/zapcore/marshaler.go
  vendor/go.uber.org/zap/zaptest/observer/logged_entry.go
  vendor/go.uber.org/zap/zaptest/observer/observer.go
  vendor/modules.txt
Labels: approved, kind/bug, lgtm, release-note, size/XL

#812 Add multi-arch builds for triggers
  tekton/publish.yaml
Labels: approved, lgtm, release-note, size/XS

#814 Fixing broken link to pipeline repo
  docs/triggertemplates.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#811 Fix GitHub and GitLab capitalization
  README.md
  docs/eventlisteners.md
  examples/bitbucket/role.yaml
  examples/cron/role.yaml
  examples/event-interceptors/main.go
  examples/github/role.yaml
  examples/gitlab/README.md
  examples/gitlab/role.yaml
  examples/role-resources/clustertriggerbinding-roles/clusterrole.yaml
  examples/role-resources/triggerbinding-roles/role.yaml
  examples/triggers/rbac.yaml
  pkg/interceptors/interceptors.go
Labels: approved, lgtm, ok-to-test, release-note-none, size/S

#815 Allow users to set resources as part of podtemplate
  docs/eventlisteners.md
  examples/github/github-eventlistener-interceptor.yaml
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, lgtm, release-note, size/L
