Repository tektoncd/triggers, pull requests merged in 2020-12, with the labels that each got.

#832 Migrate GitLab, BitBucket, GitHub interceptors to new interface
  pkg/interceptors/bitbucket/bitbucket.go
  pkg/interceptors/bitbucket/bitbucket_test.go
  pkg/interceptors/cel/cel.go
  pkg/interceptors/github/github.go
  pkg/interceptors/github/github_test.go
  pkg/interceptors/gitlab/gitlab.go
  pkg/interceptors/gitlab/gitlab_test.go
  pkg/interceptors/interceptors.go
  pkg/interceptors/interceptors_test.go
  pkg/sink/sink.go
  test/signature.go
  test/signature_test.go
Labels: approved, lgtm, release-note-none, size/XXL

#851 Add links to versioned docs for v0.10.1
  README.md
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#855 refactor: Do not use %w unless in fmt.Errorf
  cmd/triggerrun/cmd/root.go
  pkg/sink/sink.go
  test/init_test.go
Labels: approved, kind/bug, lgtm, release-note, size/S

#852 Remove deprecated fields podTemplate and serviceType
  docs/eventlisteners.md
  examples/eventlisteners/eventlistener-podtemplate.yaml
  examples/eventlisteners/eventlistener-tolerations.yaml
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  test/builder/eventlistener.go
  test/eventlistener_scale_test.go
Labels: approved, lgtm, release-note, size/L

#854 Use our own Status type for InterceptorResponse
  pkg/apis/triggers/v1alpha1/interceptor_types.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/interceptors/bitbucket/bitbucket.go
  pkg/interceptors/cel/cel.go
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/github/github.go
  pkg/interceptors/github/github_test.go
  pkg/interceptors/gitlab/gitlab.go
  pkg/interceptors/interceptors.go
Labels: approved, kind/misc, lgtm, release-note, size/L

#859 Merge extensions into body for webhook interceptors
  docs/eventlisteners.md
  pkg/interceptors/cel/cel.go
  pkg/interceptors/cel/cel_test.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
Labels: approved, kind/bug, lgtm, release-note, size/L

#860 [CHERRY-PICK] Merge extensions into body for webhook interceptors
  docs/eventlisteners.md
  pkg/interceptors/cel/cel.go
  pkg/interceptors/cel/cel_test.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
Labels: approved, lgtm, release-note, size/L

#862 Add SecurityContext to reconciled Deployment
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, lgtm, ok-to-test, release-note, size/M

#866 Remove mention of dep in dev docs
  DEVELOPMENT.md
Labels: approved, lgtm, ok-to-test, release-note-none, size/XS

#865 Add flag to disable security context on EL Deployment
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, lgtm, ok-to-test, release-note, size/S

#872 Update CRD to apiextensions.k8s.io/v1
  config/201-clusterrolebinding.yaml
  config/300-clustertriggerbinding.yaml
  config/300-eventlistener.yaml
  config/300-trigger.yaml
  config/300-triggerbinding.yaml
  config/300-triggertemplate.yaml
Labels: approved, lgtm, release-note, size/L

#873 Add @savitaashture as an OWNER 🎉
  OWNERS
Labels: approved, lgtm, release-note, size/XS

#874 add docs for installing nightly release
  docs/install.md
Labels: approved, kind/documentation, lgtm, release-note, size/S

#877 Change InterceptorRequest.Body to string
  pkg/apis/triggers/v1alpha1/interceptor_types.go
  pkg/interceptors/bitbucket/bitbucket.go
  pkg/interceptors/bitbucket/bitbucket_test.go
  pkg/interceptors/cel/cel.go
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/github/github.go
  pkg/interceptors/github/github_test.go
  pkg/interceptors/gitlab/gitlab_test.go
  pkg/interceptors/server/server_test.go
  pkg/sink/sink.go
Labels: approved, lgtm, release-note, size/M

#876 Refactor flags to improve unit tests
  cmd/controller/main.go
  pkg/reconciler/v1alpha1/eventlistener/config.go
  pkg/reconciler/v1alpha1/eventlistener/controller.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  test/eventlistener_test.go
Labels: approved, lgtm, ok-to-test, release-note, size/L

#843 Use a test helper for rawExtension objects in tests
  pkg/apis/triggers/v1alpha1/trigger_template_validation_test.go
  pkg/apis/triggers/v1alpha1/trigger_validation_test.go
Labels: approved, lgtm, ok-to-test, release-note, size/L
