Repository tektoncd/triggers, pull requests merged in 2020-04, with the labels that each got.

#511 [master] Fix spelling errors
  pkg/sink/sink_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#513 Use static selector labels for EL svc/deployments
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, cla: yes, lgtm, size/S

#512 Bump pipeline version to 0.11.0
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/condition_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipeline_conversion.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipeline_defaults.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipeline_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipeline_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipelinerun_defaults.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipelinerun_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/task_conversion.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/task_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/taskrun_conversion.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/taskrun_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/taskrun_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/param_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_defaults.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_defaults.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/task_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/task_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/taskrun_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/workspace_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/resource/v1alpha1/pipeline_resource_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/resource/v1alpha1/pipelineresource_validation.go
  vendor/github.com/tektoncd/pipeline/third_party/github.com/jenkins-x/go-scm/LICENSE
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#507 Add omitempty tag to Status field
  pkg/apis/triggers/v1alpha1/cluster_trigger_binding_types.go
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/trigger_binding_types.go
  pkg/apis/triggers/v1alpha1/trigger_template_types.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#515 Remove unused variable
  pkg/sink/sink.go
  pkg/sink/sink_test.go
Labels: approved, cla: yes, lgtm, size/S

#519 Update docs to specify k8s version 1.15 or greater
  DEVELOPMENT.md
  docs/install.md
Labels: approved, cla: yes, lgtm, size/XS

#520 Fix incorrect split example
  docs/eventlisteners.md
  examples/eventlisteners/cel-eventlistener-multiple-overlays.yaml
  pkg/interceptors/cel/cel_test.go
Labels: approved, cla: yes, lgtm, size/S

#522 Add a `releaseAsLatest` param to release pipeline
  tekton/publish.yaml
Labels: approved, cla: yes, lgtm, size/M

#524 Fix param description
  tekton/publish.yaml
Labels: approved, cla: yes, lgtm, size/XS

#521 add valid sa to trigger level auth test
  test/eventlistener_test.go
Labels: approved, cla: yes, lgtm, size/M

#528 Add links to docs & examples for v0.4.0 in README
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#530 Fix automatic deletion of Tekton logging ConfigMap.
  pkg/reconciler/v1alpha1/eventlistener/controller.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, cla: yes, lgtm, size/M

#514 Fix broken anchor link in EventListener docs
  docs/eventlisteners.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#536 Update API Group in Clusterrole Aggregate
  config/clusterrole-aggregate-edit.yaml
  config/clusterrole-aggregate-view.yaml
Labels: approved, cla: yes, lgtm, size/XS

#535 Fix image path in github validate yaml
  examples/event-interceptors/github-validate.yaml
Labels: approved, cla: yes, lgtm, size/XS

#542 Fix CEL Example for secret comparison
  examples/eventlisteners/cel-eventlistener-interceptor-with-secret.yaml
Labels: approved, cla: yes, lgtm, size/XS

#547 Add a ServiceAccount to EventListenerScaleTest
  test/eventlistener_scale_test.go
Labels: approved, cla: yes, lgtm, size/M

#467 Add Readiness Probe for EventListener Deployment
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, cla: yes, lgtm, size/M

#531 Adds an example of escaping keys with dots
  docs/triggerbindings.md
Labels: approved, cla: yes, lgtm, size/XS

#537 Implement parseJSON for strings.
  docs/cel_expressions.md
  pkg/interceptors/cel/cel.go
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/cel/functions.go
Labels: approved, cla: yes, lgtm, size/M

#550 Add version labels on CRDs 🏷
  config/300-clustertriggerbinding.yaml
  config/300-eventlistener.yaml
  config/300-triggerbinding.yaml
  config/300-triggertemplate.yaml
Labels: approved, lgtm, size/S

#551 Format logs command
  docs/getting-started/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#552 Fix typos
  README.md
  roadmap.md
  tekton/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#553 Use the same generate scripts as pipeline ⚙
  hack/generate-groups.sh
  hack/generate-knative.sh
  hack/update-codegen.sh
Labels: approved, lgtm, size/L

#555 Make webhook secret name overridable
  cmd/webhook/main.go
  config/webhook.yaml
Labels: approved, lgtm, size/XS

#560 Add missing license to the code and config
  config/clusterrole-aggregate-edit.yaml
  config/clusterrole-aggregate-view.yaml
  config/webhook-service.yaml
  pkg/apis/triggers/v1alpha1/contexts.go
  pkg/apis/triggers/v1alpha1/trigger_binding_defaults.go
  pkg/apis/triggers/v1alpha1/trigger_template_defaults.go
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/cel/functions.go
  pkg/interceptors/github/github_test.go
  pkg/sink/auth_override.go
  pkg/template/jsonpath.go
  pkg/template/jsonpath_test.go
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
  test/builder/meta.go
  test/builder/meta_test.go
  test/builder/param.go
  test/builder/param_test.go
  test/builder/triggerbinding.go
  test/builder/triggerbinding_test.go
  test/builder/triggertemplate.go
  test/builder/triggertemplate_test.go
Labels: approved, lgtm, size/L

#556 Add recommended k8s labels
  config/101-podsecuritypolicy.yaml
  config/200-clusterrole.yaml
  config/200-serviceaccount.yaml
  config/201-clusterrolebinding.yaml
  config/300-clustertriggerbinding.yaml
  config/300-eventlistener.yaml
  config/300-triggerbinding.yaml
  config/300-triggertemplate.yaml
  config/500-webhooks.yaml
  config/clusterrole-aggregate-edit.yaml
  config/clusterrole-aggregate-view.yaml
  config/config-logging.yaml
  config/config-observability.yaml
  config/controller-service.yaml
  config/controller.yaml
  config/webhook-service.yaml
  config/webhook.yaml
Labels: approved, lgtm, size/L

#562 Bump plumbing to recent master 👼
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/CONTRIBUTING.md
  vendor/github.com/tektoncd/plumbing/OWNERS
  vendor/github.com/tektoncd/plumbing/addpermissions.py
  vendor/github.com/tektoncd/plumbing/gcp.md
  vendor/github.com/tektoncd/plumbing/go.mod
  vendor/github.com/tektoncd/plumbing/go.sum
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L
