Repository tektoncd/triggers, pull requests merged in 2020-02, with the labels that each got.

#407 Update CEL docs
  docs/eventlisteners.md
  docs/triggerbindings.md
  docs/triggertemplates.md
  examples/eventlisteners/cel-eventlistener-interceptor.yaml
Labels: approved, cla: yes, lgtm, size/S

#414 Format markdown
  docs/clustertriggerbindings.md
  docs/eventlisteners.md
  docs/triggerbindings.md
  docs/triggertemplates.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#416 cel langdef doc links
  docs/cel_expressions.md
  docs/eventlisteners.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#411 Add support for splitting strings to CEL expressions.
  docs/cel_expressions.md
  pkg/interceptors/cel/cel.go
  pkg/interceptors/cel/cel_test.go
Labels: approved, cla: yes, lgtm, size/M

#420 Delete clusterscoped resource in teardown
  test/init_test.go
Labels: approved, cla: yes, lgtm, size/S

#417 Fix yaml formatting
  docs/exposing-eventlisteners.md
Labels: approved, cla: yes, lgtm, size/S

#410 Add CEL function canonical.
  docs/cel_expressions.md
  docs/clustertriggerbindings.md
  docs/eventlisteners.md
  docs/triggerbindings.md
  docs/triggertemplates.md
  examples/eventlisteners/cel-eventlistener-interceptor.yaml
  pkg/interceptors/cel/cel.go
  pkg/interceptors/cel/cel_test.go
Labels: approved, cla: yes, lgtm, size/L

#423 Format markdown
  docs/cel_expressions.md
  docs/clustertriggerbindings.md
  docs/eventlisteners.md
  docs/exposing-eventlisteners.md
  docs/triggerbindings.md
  docs/triggertemplates.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#424 Remove deprecated binding
  pkg/apis/triggers/v1alpha1/event_listener_defaults.go
  pkg/apis/triggers/v1alpha1/event_listener_defaults_test.go
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/L

#425 Remove deprecated Interceptor
  docs/clustertriggerbindings.md
  docs/eventlisteners.md
  docs/triggerbindings.md
  docs/triggertemplates.md
  pkg/apis/triggers/v1alpha1/event_listener_defaults.go
  pkg/apis/triggers/v1alpha1/event_listener_defaults_test.go
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/L

#429 Move GH-Validate Interceptor code to example
  examples/event-interceptors/github-validate.yaml
  examples/event-interceptors/main.go
Labels: approved, cla: yes, lgtm, size/XS

#433 Increase waiting timeout
  test/wait.go
Labels: approved, cla: yes, lgtm, size/XS

#430 Format markdown
  docs/clustertriggerbindings.md
  docs/eventlisteners.md
  docs/triggerbindings.md
  docs/triggertemplates.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#431 Allow keeping namespaces after running tests for investigation
  test/README.md
  test/init_test.go
Labels: approved, cla: yes, lgtm, size/S

#428 Add Version Label to Triggers Deployment & Service
  config/controller-service.yaml
  config/controller.yaml
  config/webhook-service.yaml
  config/webhook.yaml
  tekton/publish.yaml
Labels: approved, cla: yes, lgtm, size/S

#404 Add decodeb64 function to CEL expressions.
  docs/cel_expressions.md
  docs/eventlisteners.md
  examples/eventlisteners/cel-eventlistener-interceptor.yaml
  pkg/interceptors/cel/cel.go
  pkg/interceptors/cel/cel_test.go
Labels: approved, cla: yes, lgtm, size/M

#421 Fixes for the nightly release process
  tekton/publish-run.yaml
  tekton/publish.yaml
  tekton/release-pipeline-run.yaml
  tekton/release-pipeline.yaml
  tekton/resources.yaml
Labels: approved, cla: yes, lgtm, size/L

#443 Format markdown
  docs/eventlisteners.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#435 validate ObjectMetadata for TriggerTemplate
  pkg/apis/triggers/v1alpha1/trigger_template_validation.go
  pkg/apis/triggers/v1alpha1/trigger_template_validation_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#445 Add our go report card to the README
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#432 Add Liveness Probe for EventListener Deployment
  .errcheck.txt
  cmd/eventlistenersink/main.go
  config/controller.yaml
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, cla: yes, lgtm, size/M

#426 Update EventListener docs format
  docs/eventlisteners.md
  examples/role-resources/clustertriggerbinding-roles/clusterrole.yaml
  examples/role-resources/triggerbinding-roles/role.yaml
Labels: approved, cla: yes, lgtm, size/L

#444 Remove deprecated Params field from EventListener
  pkg/apis/triggers/v1alpha1/event_listener_defaults.go
  pkg/apis/triggers/v1alpha1/event_listener_defaults_test.go
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/M

#446 Fix typo cel interceptor example.
  docs/clustertriggerbindings.md
  docs/eventlisteners.md
  docs/triggerbindings.md
  docs/triggertemplates.md
  examples/eventlisteners/cel-eventlistener-interceptor.yaml
Labels: approved, cla: yes, lgtm, size/S

#448 Format markdown
  docs/clustertriggerbindings.md
  docs/eventlisteners.md
  docs/triggerbindings.md
  docs/triggertemplates.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#449 Add Regression test for large number of Triggers
  test/README.md
  test/eventlistener_scale_test.go
  test/eventlistener_test.go
  test/init_test.go
Labels: approved, cla: yes, lgtm, size/M

#451 Fix broken symbolic links in cron example
  examples/cron/binding.yaml
  examples/cron/role.yaml
Labels: approved, cla: yes, lgtm, size/XS

#434 Replace gitlab-eventlistener with a working example
  docs/eventlisteners.md
  examples/eventlisteners/gitlab-eventlistener-interceptor.yaml
  examples/gitlab/README.md
  examples/gitlab/gitlab-push-event.json
  examples/gitlab/gitlab-push-listener.yaml
Labels: approved, cla: yes, lgtm, size/L

#452 correct a misspelling
  README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#453 Update gcloud command to use dogfooding cluster
  tekton/README.md
Labels: approved, cla: yes, lgtm, size/XS

#438 Ensure Interceptor request uses HTTP POST.
  docs/eventlisteners.md
  pkg/sink/sink.go
  pkg/sink/sink_test.go
Labels: approved, cla: yes, lgtm, size/M

#455 Add links to v0.3.0 in README
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#457 Add tekton triggers logo 🐈⚽
  README.md
  tekton-triggers.png
Labels: approved, cla: yes, lgtm, size/XS

#460 header key, case-insensitive match
  docs/triggerbindings.md
  pkg/template/event.go
  pkg/template/event_test.go
  pkg/template/jsonpath.go
  pkg/template/jsonpath_test.go
Labels: approved, cla: yes, lgtm, size/L

#461 Resolve TriggerBindings with no Kind set in sink
  pkg/template/resource.go
  pkg/template/resource_test.go
Labels: approved, cla: yes, lgtm, size/S

#464 Add links to v0.3.1 in README
  README.md
Labels: approved, cla: yes, lgtm, size/XS
