Repository tektoncd/triggers, pull requests merged in 2020-08, with the labels that each got.

#696 Fix URL in Release Cheat Sheet
  tekton/release-cheat-sheet.md
Labels: approved, lgtm, size/XS

#698 Add namespace to the commands in Nginx ingress doc
  docs/exposing-eventlisteners.md
Labels: approved, lgtm, ok-to-test, size/XS

#702 Change tekton.dev to triggers.tekton.dev for e2e Tests
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#703 Add links to versioned docs for v0.7.0
  README.md
Labels: approved, lgtm, size/XS

#701 Use Kaniko instead of img in tutorial to fix permission issue
  docs/getting-started/README.md
  docs/getting-started/pipeline.yaml
Labels: approved, lgtm, ok-to-test, size/M

#694 Fix GitHub example bindings
  docs/eventlisteners.md
  examples/github/README.md
  examples/github/github-eventlistener-interceptor.yaml
  examples/github/triggerbinding.yaml
  examples/github/triggertemplate.yaml
Labels: approved, lgtm, size/L

#704 switch trigger sa ref from global to namespace scoped
  pkg/apis/triggers/v1alpha1/trigger_types.go
  pkg/apis/triggers/v1alpha1/trigger_types_convert_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/S

#710 Add khrm@ as an OWNER
  OWNERS
Labels: approved, kind/misc, lgtm, size/XS

#708 Add createResource in TriggerRun CLI
  cmd/eventlistenersink/main.go
  cmd/triggerrun/cmd/root.go
  cmd/triggerrun/cmd/root_test.go
  pkg/sink/initialization.go
Labels: approved, lgtm, size/L

#719 Mark some command tests as end-to-end
  cmd/binding-eval/cmd/root_test.go
  cmd/triggerrun/cmd/root_test.go
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#706 Cleanup Reconciler Tests in order to pick up Genreconciler updates
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, kind/cleanup, lgtm, size/XL

#720 Use another NodeSelector value in EventListener tests
  test/eventlistener_scale_test.go
  test/eventlistener_test.go
Labels: approved, kind/misc, lgtm, ok-to-test, size/XS

#717 Add validation for replicas
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  test/builder/eventlistener.go
Labels: approved, kind/feature, lgtm, size/M

#673 Fix Incorrect number of response for Forbidden err
  pkg/sink/sink.go
  pkg/sink/sink_test.go
Labels: approved, kind/bug, lgtm, size/S

#725 Update triggertemplate doc and example to use tt.params
  docs/triggertemplates.md
  examples/triggertemplates/triggertemplate.yaml
Labels: approved, kind/documentation, lgtm, size/XS

#715 Fix update deployment when there is a change in replicas
  docs/eventlisteners.md
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, lgtm, size/XS

#728 Clarify bitbucket HMAC example
  examples/bitbucket/README.md
  examples/github/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#732 Add TriggerCRD object to Known Type
  pkg/apis/triggers/v1alpha1/register.go
Labels: approved, kind/misc, lgtm, size/XS

#712 Propagate annotations from EL to svc and deployment
  docs/eventlisteners.md
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  test/builder/meta.go
  test/builder/meta_test.go
Labels: approved, lgtm, size/L
