Repository tektoncd/triggers, pull requests merged in 2020-05, with the labels that each got.

#566 Switch to ko-gcloud for release
  tekton/publish.yaml
Labels: approved, lgtm, size/XS

#569 Fix typo in EventListeners doc
  docs/eventlisteners.md
Labels: approved, lgtm, ok-to-test, size/XS

#580 Fix 'Edit this page' and 'Create an issue' links on the website
  docs/README.md
Labels: approved, lgtm, size/XS

#582 Fix link to getting started guide on website
  docs/install.md
Labels: approved, kind/documentation, lgtm, size/XS

#588 Remove linting from release pipeline 🧹
  tekton/release-pipeline.yaml
Labels: approved, lgtm, size/S
