Repository tektoncd/triggers, pull requests merged in 2020-11, with the labels that each got.

#816 Add links to versioned docs for v0.9.0 and v0.9.1
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#821 Use Listers to fetch data in the Sink
  cmd/eventlistenersink/main.go
  cmd/triggerrun/cmd/root.go
  docs/eventlisteners.md
  examples/README.md
  examples/bitbucket/role.yaml
  examples/cron/binding.yaml
  examples/cron/role.yaml
  examples/github/role.yaml
  examples/gitlab/binding.yaml
  examples/gitlab/role.yaml
  examples/role-resources/clustertriggerbinding-roles/clusterbinding.yaml
  examples/role-resources/clustertriggerbinding-roles/clusterrole.yaml
  examples/role-resources/triggerbinding-roles/role.yaml
  examples/triggers/rbac.yaml
  examples/v1alpha1-task/README.md
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  pkg/template/resource.go
  pkg/template/resource_test.go
  test/eventlistener_scale_test.go
  test/eventlistener_test.go
Labels: approved, kind/feature, lgtm, release-note, size/L

#825 Update Tekton Pipeline Dependency Version to v0.18.0
  go.mod
  go.sum
  vendor/github.com/google/go-containerregistry/LICENSE
  vendor/github.com/google/go-containerregistry/pkg/name/README.md
  vendor/github.com/google/go-containerregistry/pkg/name/check.go
  vendor/github.com/google/go-containerregistry/pkg/name/digest.go
  vendor/github.com/google/go-containerregistry/pkg/name/doc.go
  vendor/github.com/google/go-containerregistry/pkg/name/errors.go
  vendor/github.com/google/go-containerregistry/pkg/name/options.go
  vendor/github.com/google/go-containerregistry/pkg/name/ref.go
  vendor/github.com/google/go-containerregistry/pkg/name/registry.go
  vendor/github.com/google/go-containerregistry/pkg/name/repository.go
  vendor/github.com/google/go-containerregistry/pkg/name/tag.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/config/feature_flags.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/pod/doc.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/pod/template.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipeline_conversion.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/openapi_generated.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/substitution.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/swagger.json
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/task_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/task_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/taskrun_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/taskrun_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/when_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/when_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, kind/misc, lgtm, release-note-none, size/XXL

#826 Fix apiVersion for test triggerbinding
  cmd/binding-eval/testdata/triggerbinding.yaml
Labels: approved, kind/bug, lgtm, release-note, size/XS

#818 separate SAs for controller/webhook deployment to allow for different permission sets
  config/200-role.yaml
  config/200-serviceaccount.yaml
  config/201-clusterrolebinding.yaml
  config/201-rolebinding.yaml
  config/webhook.yaml
Labels: approved, lgtm, release-note-none, size/M

#829 Change the webhook name to triggers-webhook
  cmd/webhook/main.go
Labels: approved, kind/bug, lgtm, release-note, size/XS

#747 Add Timeout for EventListener Server
  cmd/eventlistenersink/main.go
  config/controller.yaml
  docs/eventlisteners.md
  pkg/interceptors/bitbucket/bitbucket_test.go
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/github/github_test.go
  pkg/interceptors/gitlab/gitlab_test.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  pkg/sink/initialization.go
Labels: approved, kind/feature, lgtm, release-note, size/M

#830 Switch webhook apiVersions to v1
  config/500-webhooks.yaml
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#823 Drop escaping of strings in the JSON.
  docs/triggertemplates.md
  pkg/template/event.go
  pkg/template/event_test.go
  pkg/template/resource.go
  pkg/template/resource_test.go
  test/eventlistener_test.go
Labels: approved, lgtm, release-note-action-required, size/L

#833 Use zaptest logger in tests
  cmd/triggerrun/cmd/root_test.go
  pkg/interceptors/bitbucket/bitbucket_test.go
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/github/github_test.go
  pkg/interceptors/gitlab/gitlab_test.go
  pkg/resources/create_test.go
  pkg/sink/sink_test.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/M

#773 Add EventListener Selector For TriggerCRD
  cmd/eventlistenersink/main.go
  cmd/triggerrun/cmd/root.go
  docs/eventlisteners.md
  examples/selectors/00_ns.yaml
  examples/selectors/01_rbac.yaml
  examples/selectors/02_eventlistener-sel.yaml
  examples/selectors/03_trigger.yaml
  examples/selectors/README.md
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/interceptors/bitbucket/bitbucket.go
  pkg/interceptors/bitbucket/bitbucket_test.go
  pkg/interceptors/cel/cel.go
  pkg/interceptors/github/github.go
  pkg/interceptors/github/github_test.go
  pkg/interceptors/gitlab/gitlab.go
  pkg/interceptors/gitlab/gitlab_test.go
  pkg/interceptors/interceptors.go
  pkg/interceptors/webhook/webhook.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/sink/initialization.go
  pkg/sink/initialization_test.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  pkg/template/resource.go
  pkg/template/resource_test.go
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
Labels: approved, kind/feature, lgtm, release-note, size/XXL

#819 Allow secure connection to eventlistener pod
  cmd/eventlistenersink/main.go
  docs/eventlisteners.md
  examples/eventlistener-tls-connection/README.md
  examples/eventlistener-tls-connection/role.yaml
  examples/eventlistener-tls-connection/secret.yaml
  examples/eventlistener-tls-connection/tls-eventlistener-interceptor.yaml
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  pkg/sink/initialization.go
Labels: approved, lgtm, release-note, size/XL

#834 Update tls example yaml
  examples/eventlistener-tls-connection/role.yaml
  examples/eventlistener-tls-connection/secret.yaml
  examples/eventlistener-tls-connection/tls-eventlistener-interceptor.yaml
Labels: approved, lgtm, release-note, size/XS

#838 Fix EL Container Arguments in Reconciler
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
Labels: approved, kind/bug, lgtm, release-note, size/S

#839 Update README for trigger selector based examples
  examples/selectors/README.md
Labels: approved, kind/documentation, lgtm, release-note, size/S

#840 Add links to versioned docs for v0.10.0
  README.md
Labels: approved, lgtm, release-note-none, size/XS

#842 Implement marshalJSON CEL function
  docs/cel_expressions.md
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/cel/triggers.go
Labels: approved, lgtm, ok-to-test, release-note, size/M

#844 Update pull request template links
  .github/pull_request_template.md
Labels: approved, kind/misc, lgtm, ok-to-test, release-note, size/XS
