Repository tektoncd/triggers, pull requests merged in 2020-06, with the labels that each got.

#587 Fix release version tag for release yaml
  tekton/publish.yaml
Labels: approved, lgtm, size/XS

#591 Add URL parsing to CEL expressions.
  docs/cel_expressions.md
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/cel/triggers.go
Labels: approved, lgtm, size/L

#593 Update README.md
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#598 Publish both tagged and untagged images for releases
  tekton/publish.yaml
Labels: approved, kind/bug, lgtm, size/XS

#600 Fix GCP setup broken link in dev docs
  DEVELOPMENT.md
Labels: approved, lgtm, ok-to-test, size/XS

#601 Update TriggerTemplate docs with supported types.
  docs/triggertemplates.md
Labels: approved, lgtm, size/S

#609 Ensure that decodeB64 returns a String rather than Bytes.
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/cel/triggers.go
Labels: approved, kind/bug, lgtm, size/M

#602 Move multi tenant section below syntax
  docs/eventlisteners.md
Labels: approved, kind/documentation, lgtm, size/L

#599 Use portforwarder instead of kubectl command line
  go.mod
  go.sum
  test/eventlistener_test.go
  vendor/github.com/docker/spdystream/CONTRIBUTING.md
  vendor/github.com/docker/spdystream/LICENSE
  vendor/github.com/docker/spdystream/LICENSE.docs
  vendor/github.com/docker/spdystream/MAINTAINERS
  vendor/github.com/docker/spdystream/README.md
  vendor/github.com/docker/spdystream/connection.go
  vendor/github.com/docker/spdystream/handlers.go
  vendor/github.com/docker/spdystream/priority.go
  vendor/github.com/docker/spdystream/spdy/dictionary.go
  vendor/github.com/docker/spdystream/spdy/read.go
  vendor/github.com/docker/spdystream/spdy/types.go
  vendor/github.com/docker/spdystream/spdy/write.go
  vendor/github.com/docker/spdystream/stream.go
  vendor/github.com/docker/spdystream/utils.go
  vendor/github.com/tektoncd/plumbing/demo
  vendor/k8s.io/apimachinery/pkg/util/httpstream/doc.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/connection.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/netutil/addr.go
  vendor/k8s.io/client-go/tools/portforward/doc.go
  vendor/k8s.io/client-go/tools/portforward/portforward.go
  vendor/k8s.io/client-go/transport/spdy/spdy.go
  vendor/modules.txt
Labels: approved, kind/cleanup, kind/flake, lgtm, ok-to-test, size/XXL

#603 Do not default EventListener trigger ref to name
  docs/eventlisteners.md
  examples/eventlisteners/cel-eventlistener-interceptor.yaml
  pkg/apis/triggers/v1alpha1/event_listener_defaults.go
  pkg/apis/triggers/v1alpha1/event_listener_defaults_test.go
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  test/e2e-tests-ingress.sh
Labels: approved, lgtm, ok-to-test, size/M

#614 Add extra columns for EventListeners
  config/300-eventlistener.yaml
Labels: approved, kind/feature, lgtm, size/S

#620 fix gosec error
  pkg/resources/create.go
Labels: approved, kind/misc, lgtm, size/XS

#597 add tolerations to eventlistener
  docs/eventlisteners.md
  examples/eventlisteners/eventlistener-tolerations.yaml
  go.mod
  go.sum
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  test/builder/eventlistener.go
  test/eventlistener_scale_test.go
  test/eventlistener_test.go
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/Makefile
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/go113.go
  vendor/github.com/pkg/errors/stack.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, size/L

#623 Fix formatting of version in config
  config/500-webhooks.yaml
  config/controller-service.yaml
  config/controller.yaml
  config/webhook-service.yaml
  config/webhook.yaml
Labels: approved, kind/bug, lgtm, size/S

#596 Modify BitBucketInterceptor to BitbucketInterceptor
  docs/eventlisteners.md
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/interceptors/bitbucket/bitbucket.go
  pkg/interceptors/bitbucket/bitbucket_test.go
  pkg/sink/sink_test.go
Labels: approved, lgtm, size/M

#631 Fix the Data Race in portforward e2e test of EventListener
  test/buffer.go
  test/eventlistener_test.go
Labels: approved, lgtm, size/M

#589 Modify spec params to avoid confusion between resourcetemplates and triggertemplate params
  docs/triggertemplates.md
  examples/bitbucket/triggertemplate.yaml
  examples/github/triggertemplate.yaml
  examples/gitlab/gitlab-push-listener.yaml
  examples/triggertemplates/triggertemplate.yaml
  pkg/apis/triggers/v1alpha1/trigger_template_validation.go
  pkg/apis/triggers/v1alpha1/trigger_template_validation_test.go
  pkg/sink/sink_test.go
  pkg/template/event_test.go
  pkg/template/resource.go
  pkg/template/resource_test.go
  test/eventlistener_test.go
Labels: approved, lgtm, size/L

#324 Tool for evaluating trigger bindings.
  cmd/binding-eval/cmd/root.go
  cmd/binding-eval/cmd/root_test.go
  cmd/binding-eval/main.go
  cmd/binding-eval/testdata/http.txt
  cmd/binding-eval/testdata/triggerbinding.yaml
  docs/triggerbindings.md
  go.mod
  go.sum
  pkg/template/event.go
  third_party/LICENSE
  third_party/github.com/spf13/cobra/LICENSE.txt
  third_party/vendor/golang.org/x/crypto/LICENSE
  third_party/vendor/golang.org/x/net/LICENSE
  third_party/vendor/golang.org/x/sys/cpu/LICENSE
  third_party/vendor/golang.org/x/text/LICENSE
  vendor/github.com/inconshreveable/mousetrap/LICENSE
  vendor/github.com/inconshreveable/mousetrap/README.md
  vendor/github.com/inconshreveable/mousetrap/trap_others.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows_1.4.go
  vendor/github.com/spf13/cobra/.gitignore
  vendor/github.com/spf13/cobra/.mailmap
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/LICENSE.txt
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_notwin.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/powershell_completions.md
  vendor/github.com/spf13/cobra/shell_completions.go
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/github.com/spf13/cobra/zsh_completions.md
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#634 Add missing license information
  cmd/binding-eval/cmd/root.go
  cmd/binding-eval/cmd/root_test.go
  cmd/binding-eval/main.go
  test/buffer.go
Labels: approved, kind/misc, lgtm, size/M

#633 Fix publish-tekton-triggers task
  tekton/publish.yaml
Labels: approved, kind/bug, lgtm, size/S

#637 Add cel filter for pull request actions in github example
  docs/eventlisteners.md
  examples/github/README.md
  examples/github/github-eventlistener-interceptor.yaml
Labels: approved, kind/documentation, lgtm, ok-to-test, size/XS

#636 Add CEL function to parse YAML
  docs/cel_expressions.md
  go.mod
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/cel/triggers.go
Labels: approved, lgtm, size/M

#645 Update docs and examples to use ref instead of name for bindings
  docs/eventlisteners.md
  docs/triggerbindings.md
  examples/bitbucket/bitbucket-eventlistener-interceptor.yaml
  examples/cron/eventlistener.yaml
  examples/github/README.md
  examples/gitlab/gitlab-push-listener.yaml
Labels: approved, kind/documentation, lgtm, size/M

#647 Expose the incoming request URL to CEL expressions.
  docs/cel_expressions.md
  pkg/interceptors/cel/cel.go
  pkg/interceptors/cel/cel_test.go
Labels: approved, kind/feature, lgtm, size/M

#646 Improve the error from the context evaluation.
  pkg/interceptors/cel/cel.go
  pkg/interceptors/cel/cel_test.go
Labels: approved, lgtm, size/M

#648 Add links to docs for v0.6.0
  README.md
Labels: approved, kind/misc, lgtm, size/XS
