Repository tektoncd/triggers, pull requests merged in 2020-07, with the labels that each got.

#628 Add a new CRD type called Trigger
  config/200-clusterrole.yaml
  config/300-trigger.yaml
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/trigger_types.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/triggers/v1alpha1/fake/fake_trigger.go
  pkg/client/clientset/versioned/typed/triggers/v1alpha1/fake/fake_triggers_client.go
  pkg/client/clientset/versioned/typed/triggers/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/triggers/v1alpha1/trigger.go
  pkg/client/clientset/versioned/typed/triggers/v1alpha1/triggers_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/triggers/v1alpha1/interface.go
  pkg/client/informers/externalversions/triggers/v1alpha1/trigger.go
  pkg/client/injection/informers/triggers/v1alpha1/trigger/fake/fake.go
  pkg/client/injection/informers/triggers/v1alpha1/trigger/trigger.go
  pkg/client/listers/triggers/v1alpha1/expansion_generated.go
  pkg/client/listers/triggers/v1alpha1/trigger.go
  third_party/LICENSE
  third_party/vendor/golang.org/x/crypto/LICENSE
  third_party/vendor/golang.org/x/net/LICENSE
  third_party/vendor/golang.org/x/sys/cpu/LICENSE
  third_party/vendor/golang.org/x/text/LICENSE
Labels: approved, kind/misc, lgtm, size/L

#642 Fix getting-started triggers
  docs/README.md
  docs/getting-started/01-namespace.yaml
  docs/getting-started/README.md
  docs/getting-started/create-ingress.yaml
  docs/getting-started/create-webhook.yaml
  docs/getting-started/triggers.yaml
  test/e2e-tests-ingress.sh
  test/e2e-tests-yaml.sh
Labels: approved, kind/bug, lgtm, size/M

#659 change token to secret
  examples/gitlab/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#655 Fix License copyright year
  pkg/apis/triggers/v1alpha1/trigger_types.go
Labels: approved, lgtm, size/XS

#658 Fix the declarations for compareSecret.
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/cel/triggers.go
Labels: approved, kind/bug, lgtm, size/S

#663 Use sets.NewString instead of map[string]struct{}
  pkg/apis/triggers/v1alpha1/trigger_binding_validation.go
  pkg/apis/triggers/v1alpha1/trigger_template_validation.go
Labels: approved, kind/cleanup, lgtm, size/S

#664 Add EventListener Response in the Doc
  docs/eventlisteners.md
Labels: approved, kind/documentation, lgtm, size/S

#666 Ensure that the JSON matches.
  pkg/interceptors/cel/cel_test.go
Labels: approved, kind/flake, lgtm, size/S

#657 Pass url through
  pkg/sink/sink.go
  pkg/sink/sink_test.go
Labels: approved, lgtm, size/M

#668 Support for marshaling other types.
  pkg/interceptors/cel/cel.go
  pkg/interceptors/cel/cel_test.go
Labels: approved, kind/feature, lgtm, size/M

#662 Add CLI for manual trigger runs (Parse yaml file and read HTTP)
  cmd/triggerRun/cmd/root.go
  cmd/triggerRun/cmd/root_test.go
  cmd/triggerRun/main.go
  cmd/triggerRun/testdata/http.txt
  cmd/triggerRun/testdata/trigger.yaml
  go.sum
  pkg/apis/triggers/v1alpha1/trigger_types.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#671 Add links to versioned docs for v0.6.1
  README.md
Labels: approved, kind/documentation, lgtm, size/XS

#670 Replace old Release docs in favor of a cheat sheet
  tekton/README.md
  tekton/release-cheat-sheet.md
  tekton/resources.yaml
Labels: approved, kind/documentation, lgtm, size/L

#625 add nodeSelector and replicas to eventlistener
  docs/eventlisteners.md
  examples/eventlisteners/eventlistener-podtemplate.yaml
  examples/eventlisteners/eventlistener-replicas.yaml
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  test/builder/eventlistener.go
  test/eventlistener_scale_test.go
  test/eventlistener_test.go
  third_party/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
Labels: approved, kind/feature, lgtm, ok-to-test, size/L

#672 Switch to nonroot images for Triggers
  .ko.yaml
Labels: approved, lgtm, size/XS

#677 Remove unused Ref from EventListenerTrigger
  pkg/apis/triggers/v1alpha1/event_listener_types.go
Labels: approved, kind/cleanup, lgtm, size/XS

#669 Provide the incoming EventListener URL to the Webhook Interceptor.
  docs/eventlisteners.md
  pkg/interceptors/webhook/webhook.go
  pkg/interceptors/webhook/webhook_test.go
Labels: approved, kind/feature, lgtm, size/S

#676 Add ToEventListenerTrigger conversion func.
  pkg/apis/triggers/v1alpha1/trigger_types_convert.go
  pkg/apis/triggers/v1alpha1/trigger_types_convert_test.go
Labels: approved, lgtm, size/L

#683 Fix Spelling Mistake in TestCase
  pkg/sink/sink_test.go
Labels: approved, kind/misc, lgtm, size/XS

#684 Update tektoncd/pipeline to v0.14.2.
  go.mod
  go.sum
  vendor/github.com/tektoncd/pipeline/pkg/apis/config/default.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/config/feature_flags.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/config/store.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/config/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/conversion_error.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1/pipeline_conversion.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_defaults.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/resource_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/taskrun_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#688 Fix typo in README.md of getting started
  docs/getting-started/README.md
Labels: approved, kind/misc, lgtm, ok-to-test, size/XS

#689 Prevent double-logging of interceptor errors.
  pkg/sink/sink.go
Labels: approved, kind/cleanup, lgtm, size/XS

#685 Fix install links for nginx ingress for GKE
  docs/exposing-eventlisteners.md
Labels: approved, kind/documentation, lgtm, size/XS

#686 Add processTriggerSpec func to wire it to Trigger, and the corresponding unit test
  cmd/triggerRun/cmd/root.go
  cmd/triggerRun/cmd/root_test.go
Labels: approved, lgtm, size/L

#691 Fix triggertemplate validation to validate missing spec field
  pkg/apis/triggers/v1alpha1/trigger_template_validation.go
  pkg/apis/triggers/v1alpha1/trigger_template_validation_test.go
Labels: approved, lgtm, size/XS

#690 Remove deprecated $(params) to avoid confusion between resourcetemplates and triggertemplate params
  cmd/triggerRun/cmd/root_test.go
  docs/getting-started/triggers.yaml
  examples/github/triggertemplate.yaml
  pkg/apis/triggers/v1alpha1/trigger_template_validation.go
  pkg/apis/triggers/v1alpha1/trigger_template_validation_test.go
  pkg/sink/sink_test.go
  pkg/template/resource.go
  pkg/template/resource_test.go
Labels: approved, lgtm, size/L

#693 Fix Release Cheat Sheet
  tekton/release-cheat-sheet.md
Labels: approved, kind/documentation, lgtm, size/XS

#692 Use ko:// prefix for all images
  config/controller.yaml
  config/webhook.yaml
  examples/event-interceptors/github-validate.yaml
Labels: approved, kind/cleanup, lgtm, size/XS
