Repository tektoncd/triggers, pull requests merged in 2020-03, with the labels that each got.

#413 Clean up sink_test.go
  pkg/sink/initialization.go
  pkg/sink/initialization_test.go
  pkg/sink/sink_test.go
  test/controller.go
  test/controller_test.go
Labels: approved, cla: yes, lgtm, size/L

#465 Format markdown
  docs/triggerbindings.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#466 Update release README
  tekton/README.md
  tekton/create-draft-triggers-release.yaml
  tekton/resources.yaml
Labels: approved, cla: yes, lgtm, size/L

#468 Format markdown
  tekton/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#471 fix instructions in README
  examples/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#470 Support JSON double values being reencoded in the CEL interceptor
  docs/cel_expressions.md
  pkg/interceptors/cel/cel.go
  pkg/interceptors/cel/cel_test.go
Labels: approved, cla: yes, lgtm, size/L

#474 Format markdown
  docs/cel_expressions.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#477 Fix inaccurate docs about TriggerTemplate
  README.md
  docs/triggertemplates.md
Labels: approved, cla: yes, lgtm, size/XS

#475 Add additional documentation.
  docs/eventlisteners.md
  examples/eventlisteners/cel-eventlistener-multiple-overlays.yaml
  examples/triggerbindings/cel-example-trigger-binding.yaml
Labels: approved, cla: yes, lgtm, size/L

#488 [master] Format markdown
  docs/triggertemplates.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#493 [master] Format markdown
  docs/eventlisteners.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#490 Allow creating v1beta1 resources
  docs/getting-started/ingress-run.yaml
  docs/getting-started/pipeline.yaml
  docs/getting-started/webhook-run.yaml
  docs/triggertemplates.md
  examples/example-pipeline.yaml
  examples/triggertemplates/triggertemplate.yaml
  examples/v1alpha1-task/README.md
  examples/v1alpha1-task/v1alpha1-task-listener.yaml
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/trigger_binding_types.go
  pkg/apis/triggers/v1alpha1/trigger_binding_validation.go
  pkg/apis/triggers/v1alpha1/trigger_template_types.go
  pkg/apis/triggers/v1alpha1/trigger_template_validation.go
  pkg/apis/triggers/v1alpha1/trigger_template_validation_test.go
  pkg/client/dynamic/clientset/tekton/tekton.go
  pkg/interceptors/webhook/webhook.go
  pkg/interceptors/webhook/webhook_test.go
  pkg/sink/sink_test.go
  pkg/template/event.go
  pkg/template/event_test.go
  pkg/template/resource.go
  pkg/template/resource_test.go
  test/builder/clustertriggerbinding_test.go
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
  test/builder/param.go
  test/builder/param_test.go
  test/builder/triggerbinding.go
  test/builder/triggerbinding_test.go
  test/builder/triggertemplate.go
  test/builder/triggertemplate_test.go
  test/params.go
Labels: approved, cla: yes, lgtm, size/L

#502 Change api version
  docs/create-ingress.yaml
  docs/create-webhook.yaml
  docs/getting-started/ingress-run.yaml
  docs/getting-started/webhook-run.yaml
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  test/e2e-tests-ingress.sh
Labels: approved, cla: yes, lgtm, size/L

#498 Add 2020 roadmap 🛣️
  README.md
  roadmap.md
Labels: approved, cla: yes, lgtm, size/S

#503 Cleanup cluster resources when test fails
  test/eventlistener_test.go
Labels: approved, cla: yes, lgtm, size/M

#492 Implement constant-time secret comparisons in CEL.
  docs/cel_expressions.md
  examples/eventlisteners/cel-eventlistener-interceptor-with-secret.yaml
  pkg/interceptors/cel/cel.go
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/cel/functions.go
  pkg/sink/sink.go
Labels: approved, cla: yes, lgtm, size/L

#454 introduce authentication/authorization at the EventListenerTrigger le…
  cmd/eventlistenersink/main.go
  docs/clustertriggerbindings.md
  docs/eventlisteners.md
  docs/triggerbindings.md
  docs/triggertemplates.md
  examples/role-resources/clustertriggerbinding-roles/clusterrole.yaml
  examples/role-resources/triggerbinding-roles/role.yaml
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/resources/create.go
  pkg/sink/auth_override.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  test/builder/eventlistener.go
  test/controller.go
  test/eventlistener_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL
