Repository tektoncd/triggers, pull requests merged in 2020-01, with the labels that each got.

#303 Fix codeblock types in examples/README.md.
  docs/exposing-eventlisteners.md
  examples/README.md
Labels: approved, lgtm, size/XS

#305 Fix different uid generated in one triggerTemplate
  pkg/template/event.go
  pkg/template/event_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#288 Validate ResourceTemplate params are declared
  pkg/apis/triggers/v1alpha1/trigger_template_validation.go
  pkg/apis/triggers/v1alpha1/trigger_template_validation_test.go
Labels: approved, lgtm, size/M

#315 Fix AddLabels panic nil map bug
  pkg/resources/create.go
  pkg/resources/create_test.go
Labels: approved, lgtm, size/L

#317 Align spaces in readme
  examples/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#319 Define ElPort to config port of eventListener, keep default value to 8080
  config/controller.yaml
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  test/eventlistener_test.go
Labels: approved, lgtm, ok-to-test, size/M

#316 Update documentation to embed PipeineResources
  docs/getting-started/triggers.yaml
  docs/triggerbindings.md
  docs/triggertemplates.md
  examples/README.md
  examples/eventlisteners/eventlistener.yaml
  examples/triggerbindings/triggerbinding-message.yaml
  examples/triggertemplates/triggertemplate.yaml
Labels: approved, lgtm, size/L

#321 Split Test_NewResources into smaller tests
  pkg/template/event.go
  pkg/template/event_test.go
  pkg/template/resource_test.go
  test/builder/param.go
  test/builder/param_test.go
Labels: approved, lgtm, size/XL

#326 Use RoundTripper-like interface for interceptors.
  docs/eventlisteners.md
  pkg/interceptors/cel/cel.go
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/github/github.go
  pkg/interceptors/github/github_test.go
  pkg/interceptors/gitlab/gitlab.go
  pkg/interceptors/gitlab/gitlab_test.go
  pkg/interceptors/interceptors.go
  pkg/interceptors/webhook/interceptors.go
  pkg/interceptors/webhook/interceptors_test.go
  pkg/interceptors/webhook/sink.go
  pkg/interceptors/webhook/sink_test.go
  pkg/interceptors/webhook/webhook.go
  pkg/interceptors/webhook/webhook_test.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
Labels: approved, lgtm, size/XL

#331 Drop unused KubeClientSet from the CEL interceptor.
  pkg/interceptors/cel/cel.go
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/gitlab/gitlab.go
  pkg/sink/sink.go
Labels: approved, lgtm, ok-to-test, size/S

#335 Regression: Add back interceptor errors for non-OK status codes.
  docs/eventlisteners.md
  pkg/interceptors/webhook/webhook.go
  pkg/interceptors/webhook/webhook_test.go
Labels: approved, lgtm, size/M

#337 Remove import of github.com/pkg/errors.
  pkg/interceptors/webhook/webhook.go
  pkg/interceptors/webhook/webhook_test.go
Labels: approved, lgtm, size/S

#327 Update service ports name following istio-naming convention - https:/…
  config/controller-service.yaml
  config/webhook-service.yaml
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, lgtm, ok-to-test, size/S

#345 Use serviceAccountName in getting started webhook-run example
  docs/getting-started/webhook-run.yaml
Labels: approved, lgtm, size/XS

#343 Return valid arrays for multiple JSONPath results
  docs/triggerbindings.md
  pkg/template/jsonpath.go
  pkg/template/jsonpath_test.go
Labels: approved, lgtm, size/L

#348 Add @wlynch as an OWNER ⚡
  OWNERS
Labels: approved, lgtm, size/XS

#342 Fix incorrect triggerBindinging example
  docs/triggerbindings.md
Labels: approved, lgtm, size/XS

#344 Format markdown and update update-docs script
  hack/update-docs.sh
Labels: approved, lgtm, size/XS

#352 Document exposing EL with openshift route
  docs/exposing-eventlisteners.md
Labels: approved, lgtm, size/S

#354 Format markdown
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
  code-of-conduct.md
  docs/README.md
  docs/cel_expressions.md
  docs/eventlisteners.md
  docs/exposing-eventlisteners.md
  docs/getting-started/README.md
  docs/install.md
  docs/triggerbindings.md
  docs/triggertemplates.md
  examples/README.md
  examples/cron/README.md
  tekton/README.md
  test/README.md
  test/builder/README.md
Labels: approved, lgtm, ok-to-test, size/XL

#364 Format markdown
  examples/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#357 fix panic in github interceptor
  pkg/interceptors/cel/cel.go
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/github/github.go
  pkg/interceptors/github/github_test.go
  pkg/resources/create.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
Labels: approved, lgtm, size/L

#374 Fix cel interceptors documentation example
  docs/eventlisteners.md
  examples/eventlisteners/cel-eventlistener-interceptor.yaml
Labels: approved, lgtm, size/XS

#377 Add docs and examples links for v0.2.0
  README.md
Labels: approved, kind/documentation, lgtm, size/XS

#376 Allow brackets inside Tekton expressions
  docs/triggerbindings.md
  pkg/template/event.go
  pkg/template/event_test.go
  pkg/template/jsonpath.go
  pkg/template/jsonpath_test.go
Labels: approved, lgtm, size/L

#383 Validate EventListener trigger name as label value
  docs/eventlisteners.md
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
Labels: approved, lgtm, size/M

#388 Fix bug running multiple triggers
  pkg/sink/sink.go
  pkg/sink/sink_test.go
Labels: approved, lgtm, size/L

#384 Fix a few docs issues
  docs/eventlisteners.md
  docs/triggerbindings.md
  docs/triggertemplates.md
  examples/eventlisteners/eventlistener-multiinterceptor.yaml
  examples/eventlisteners/github-eventlistener-interceptor.yaml
  examples/eventlisteners/gitlab-eventlistener-interceptor.yaml
  examples/role-resources/role.yaml
  tekton/README.md
Labels: approved, lgtm, size/M

#389 Cleanup comments in sink_test.go
  pkg/sink/sink_test.go
Labels: approved, lgtm, size/XS

#393 Fix interceptors receiving incorrect headers
  pkg/sink/sink.go
  pkg/sink/sink_test.go
Labels: approved, lgtm, size/L

#397 Remove debug print statement in sink_test.go
  pkg/sink/sink_test.go
Labels: approved, lgtm, size/XS

#381 Add .gitattributes information on generated files 🍥
  .gitattributes
Labels: approved, lgtm, size/XS

#360 Use `tekton` instead of all as categories 🎿
  config/300-eventlistener.yaml
  config/300-triggerbinding.yaml
  config/300-triggertemplate.yaml
Labels: approved, lgtm, size/XS

#399 Fix interceptors receiving incorrect headers
  pkg/sink/sink.go
  pkg/sink/sink_test.go
Labels: approved, cla: yes, lgtm, size/L

#400 [cherry-pick #394]: Remove debug print statement in sink_test.go
  pkg/sink/sink_test.go
Labels: approved, cla: yes, lgtm, size/XS

#398 Fix lint issue
  .errcheck.txt
  .golangci.yml
Labels: approved, lgtm, size/S

#395 Format markdown
  docs/eventlisteners.md
  docs/triggerbindings.md
  docs/triggertemplates.md
Labels: approved, lgtm, ok-to-test, size/S

#401 Fix e2e tests
  test/e2e-common.sh
  test/e2e-tests-ingress.sh
Labels: approved, cla: yes, lgtm, size/S

#402 Replace doc links to v0.2.0 with links to v0.2.1
  README.md
Labels: approved, cla: yes, lgtm, size/XS
