Repository tektoncd/triggers, pull requests merged in 2021-02, with the labels that each got.

#935 Add validation to the length of EventListener name
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
Labels: approved, lgtm, ok-to-test, release-note, size/S

#937 Make test names consistent in reconciler
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, kind/cleanup, lgtm, release-note, size/M

#939 Use generateName instead of $(uid) for metadata.name
  docs/getting-started/triggers.yaml
Labels: approved, kind/bug, lgtm, release-note, size/XS

#950 Add kustomize.yaml to the Tekton folder
  tekton/kustomization.yaml
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#947 Adding tests for cel expressions demonstrating use of has
  pkg/interceptors/cel/cel_test.go
Labels: approved, lgtm, ok-to-test, release-note-none, size/S

#954 Add some documentation around debugging EventListeners.
  docs/debugging-eventlisteners.md
  docs/exposing-eventlisteners.md
  pkg/sink/sink.go
Labels: approved, lgtm, release-note-none, size/L

#956 Fix container name in Deployment for interceptors
  config/interceptors.yaml
Labels: approved, lgtm, release-note, size/XS

#957 Use tekton beta resources for build
  tekton/create-draft-triggers-release.yaml
  tekton/publish.yaml
  tekton/release-pipeline.yaml
Labels: approved, kind/misc, lgtm, release-note-none, size/L

#963 doc: template inside a Trigger is not optional
  docs/triggers.md
Labels: approved, kind/documentation, lgtm, release-note, size/XS

#965 Use golang-build-legacy and golang-test-legacy.
  tekton/release-pipeline.yaml
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#966 Rewrite the Tekton Triggers installation instructions for clarity and flow
  docs/install.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/M

#972 Write a new Tekton Triggers Overview
  docs/README.md
Labels: approved, lgtm, release-note-none, size/M

#975 Update to match the new /docs/README.md Triggers Overview from PR 972
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/M
