Repository tektoncd/triggers, pull requests merged in 2021-12, with the labels that each got.

#1280 Fix incorrect heading indentation
  docs/eventlisteners.md
Labels: documentation, kind/documentation, release-note, lgtm, size/XS, approved

#1273 Unregister unnecessary configMap informer
  pkg/reconciler/eventlistener/controller.go
  pkg/reconciler/eventlistener/eventlistener.go
  test/controller.go
  test/controller_test.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/configmap/configmap.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/configmap/fake/fake.go
  vendor/modules.txt
Labels: release-note, lgtm, size/L, approved, kind/cleanup

#1277 Add validation for eventlistener spec
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1beta1/event_listener_validation.go
  pkg/apis/triggers/v1beta1/event_listener_validation_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M

#1267 Update Triggers cluster role to work with Owner References
  config/200-clusterrole.yaml
Labels: kind/bug, release-note, lgtm, size/XS, approved

#1282 Fix eventlistener crash with multiple interceptors extensions
  pkg/sink/sink.go
  pkg/sink/sink_test.go
Labels: ok-to-test, release-note, lgtm, size/L, approved

#1222 Add kubernetes based events for triggers
  config/200-clusterrole.yaml
  docs/events.md
  pkg/adapter/adapter.go
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_types_test.go
  pkg/apis/triggers/v1beta1/event_listener_types.go
  pkg/apis/triggers/v1beta1/event_listener_types_test.go
  pkg/reconciler/eventlistener/eventlistener.go
  pkg/reconciler/events/doc.go
  pkg/reconciler/events/event.go
  pkg/reconciler/events/event_test.go
  pkg/sink/initialization.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  pkg/sink/validate_payload_test.go
Labels: release-note, lgtm, size/L, approved

#1283 Allow creating v1alpha1 Run types
  pkg/client/dynamic/clientset/tekton/tekton.go
Labels: release-note, lgtm, size/XS, approved

#1281 Remove replace directives in go.mod
  go.mod
  go.sum
  vendor/modules.txt
Labels: release-note, lgtm, approved, size/S

#1286 Add linux/arm to the list of platforms we build
  tekton/release-pipeline.yaml
Labels: release-note, lgtm, size/XS, approved

#1264 Add validation to validate TriggerBinding Spec
  pkg/apis/triggers/v1alpha1/cluster_trigger_binding_validation_test.go
  pkg/apis/triggers/v1alpha1/trigger_binding_validation.go
  pkg/apis/triggers/v1alpha1/trigger_binding_validation_test.go
  pkg/apis/triggers/v1beta1/cluster_trigger_binding_validation_test.go
  pkg/apis/triggers/v1beta1/trigger_binding_validation.go
  pkg/apis/triggers/v1beta1/trigger_binding_validation_test.go
Labels: release-note, lgtm, approved, size/M

#1285 Add a RegisterInterceptor helper function
  pkg/interceptors/server/server.go
  pkg/interceptors/server/server_test.go
Labels: lgtm, approved, size/M, release-note-none

#1287 Use the same mechanism to load kubeconfig
  cmd/interceptors/main.go
Labels: release-note, lgtm, size/XS, approved

#1288 Refresh TriggerBinding docs
  docs/triggerbindings.md
Labels: release-note, lgtm, approved, size/M

#1289 Update docs on exposing EventListeners
  docs/eventlisteners.md
Labels: kind/documentation, release-note, lgtm, approved, size/M

#1291 Update roles for events
  config/200-clusterrole.yaml
Labels: kind/bug, release-note, lgtm, size/XS, approved, kind/misc
