Repository tektoncd/triggers, pull requests merged in 2021-03, with the labels that each got.

#958 Add support for custom object to triggers eventlistener
  config/200-clusterrole.yaml
  config/300-eventlistener.yaml
  docs/eventlisteners.md
  examples/custom-resource/README.md
  examples/custom-resource/github-knative-listener-customresource.yaml
  examples/custom-resource/rbac.yaml
  examples/custom-resource/secret.yaml
  examples/rbac.yaml
  go.mod
  go.sum
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_types_test.go
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/dynamic/custom_reconcile.go
  pkg/dynamic/custom_reconcile_test.go
  pkg/dynamic/dynamic.go
  pkg/reconciler/v1alpha1/eventlistener/controller.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  test/controller.go
  test/controller_test.go
  test/wait.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/podspecable/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/podspecable/podspecable.go
  vendor/knative.dev/pkg/injection/clients/dynamicclient/dynamicclient.go
  vendor/knative.dev/pkg/injection/clients/dynamicclient/fake/fake.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/XXL

#969 Validate Event Body for Json Format
  cmd/eventlistenersink/main.go
  pkg/sink/sink.go
  pkg/sink/validate_payload.go
  pkg/sink/validate_payload_test.go
Labels: approved, lgtm, release-note, size/L

#978 Fix broken link to Getting Started
  README.md
Labels: approved, lgtm, ok-to-test, release-note, size/XS

#979 fix a typo
  docs/README.md
Labels: approved, lgtm, ok-to-test, release-note, size/XS

#981 Rewrite triggertemplates.md for clarity and flow
  docs/triggertemplates.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/L

#984 Correct eventlistener docs to properly set service account for a trigger
  docs/eventlisteners.md
Labels: approved, lgtm, ok-to-test, release-note-none, size/XS

#982 Add link to versioned docs for v0.12.0
  README.md
Labels: approved, lgtm, release-note, size/XS

#987 Update triggers, community and cli reference to use main…
  README.md
  docs/README.md
  docs/debugging-eventlisteners.md
  docs/getting-started/triggers.yaml
  docs/install.md
  docs/triggertemplates.md
  examples/bitbucket/README.md
  examples/github/README.md
  examples/gitlab/README.md
  examples/gitlab/gitlab-push-event.json
  examples/selectors/README.md
  examples/triggers/triggertemplate.yaml
  examples/triggertemplates/triggertemplate.yaml
Labels: approved, kind/misc, lgtm, release-note-none, size/M

#988 Rewrite triggerbindings.md for clarity and flow
  docs/triggerbindings.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/L

#989 fix: Cron task needs to post json body
  examples/cron/cronjob.yaml
Labels: approved, lgtm, ok-to-test, release-note-none, size/XS

#991 Update descriptions for `TriggerTemplates` and `TriggerBindings`
  docs/README.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/S

#992 Rewrite triggers.md for clarity and flow
  docs/triggers.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/M

#995 Fix reconciler issue while creating knative service
  examples/custom-resource/README.md
  pkg/dynamic/custom_reconcile.go
  pkg/dynamic/custom_reconcile_test.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, lgtm, release-note, size/XL

#997 [CHERRY-PICK] Fix reconciler issue while creating knative service
  examples/custom-resource/README.md
  pkg/dynamic/custom_reconcile.go
  pkg/dynamic/custom_reconcile_test.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, lgtm, release-note, size/XL

#998 [CHERRY-PICK] Fix reconciler issue while creating knative service
  examples/custom-resource/README.md
  pkg/dynamic/custom_reconcile.go
  pkg/dynamic/custom_reconcile_test.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, lgtm, release-note, size/XL

#999 Add links to versioned docs for v0.12.1
  README.md
Labels: approved, lgtm, release-note, size/XS

#976 Migrate core interceptors to use InterceptorType CRD
  DEVELOPMENT.md
  cmd/eventlistenersink/main.go
  config/interceptors/core-interceptors-deployment.yaml
  config/interceptors/core-interceptors.yaml
  go.sum
  pkg/apis/triggers/v1alpha1/cluster_interceptor_validation.go
  pkg/apis/triggers/v1alpha1/trigger_types.go
  pkg/apis/triggers/v1alpha1/trigger_types_test.go
  pkg/interceptors/interceptors.go
  pkg/interceptors/interceptors_test.go
  pkg/reconciler/v1alpha1/clusterinterceptor/controller.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  test/controller.go
  test/e2e-common.sh
  test/eventlistener_test.go
Labels: approved, lgtm, release-note, size/XL

#1004 Rewrite debugging-eventlisteners.md for clarity and flow
  docs/debugging-eventlisteners.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/M

#1011 Delete obsolete file; content merged into triggerbindings.md
  docs/clustertriggerbindings.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/M

#1007 Update publish task to include core interceptors
  tekton/publish.yaml
  tekton/release-cheat-sheet.md
Labels: approved, lgtm, release-note, size/S

#1001 Add API to configure Interceptors from a Trigger
  docs/clusterinterceptors.md
  docs/eventlisteners.md
  docs/triggers.md
  examples/bitbucket/bitbucket-eventlistener-interceptor.yaml
  examples/bitbucket/bitbucket-listener.yaml
  examples/custom-resource/github-knative-listener-customresource.yaml
  examples/eventlistener-tls-connection/tls-eventlistener-interceptor.yaml
  examples/eventlisteners/cel-eventlistener-interceptor-with-secret.yaml
  examples/eventlisteners/cel-eventlistener-interceptor.yaml
  examples/eventlisteners/cel-eventlistener-multiple-overlays.yaml
  examples/eventlisteners/cel-eventlistener-no-filter.yaml
  examples/eventlisteners/eventlistener-multiinterceptor.yaml
  examples/github/github-eventlistener-interceptor.yaml
  examples/gitlab/gitlab-push-listener.yaml
  examples/triggers/trigger.yaml
  examples/webhook-interceptors/github-validate.yaml
  examples/webhook-interceptors/main.go
  go.mod
  go.sum
  pkg/apis/triggers/v1alpha1/event_listener_defaults.go
  pkg/apis/triggers/v1alpha1/event_listener_defaults_test.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/interceptor_types.go
  pkg/apis/triggers/v1alpha1/trigger_defaults.go
  pkg/apis/triggers/v1alpha1/trigger_defaults_test.go
  pkg/apis/triggers/v1alpha1/trigger_types.go
  pkg/apis/triggers/v1alpha1/trigger_types_test.go
  pkg/apis/triggers/v1alpha1/trigger_validation.go
  pkg/apis/triggers/v1alpha1/trigger_validation_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/interceptors/interceptors.go
  pkg/interceptors/interceptors_test.go
  pkg/interceptors/server/server.go
  pkg/reconciler/v1alpha1/clusterinterceptor/controller.go
  pkg/sink/sink_test.go
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
  test/builder/trigger.go
  test/builder/trigger_test.go
  test/e2e-common.sh
  test/eventlistener_test.go
  test/json.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/XL

#1016 Update selector RBAC to include ClusterInterceptor
  examples/selectors/01_rbac.yaml
Labels: approved, lgtm, release-note, size/XS

#970 Adding label selector for triggers
  docs/eventlisteners.md
  examples/selectors/label/00_ns.yaml
  examples/selectors/label/01_rbac.yaml
  examples/selectors/label/02_eventlistener-label-sel.yaml
  examples/selectors/label/03_labeled-triggers.yaml
  examples/selectors/label/README.md
  examples/selectors/namespace/00_ns.yaml
  examples/selectors/namespace/01_rbac.yaml
  examples/selectors/namespace/02_eventlistener-ns-sel.yaml
  examples/selectors/namespace/03_trigger.yaml
  examples/selectors/namespace/README.md
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/L

#1002 Added URL field to WebhookInterceptor
  pkg/apis/triggers/v1alpha1/trigger_types.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/interceptors/webhook/webhook.go
  pkg/interceptors/webhook/webhook_test.go
Labels: approved, lgtm, ok-to-test, release-note, size/M

#1017 Added check for empty secret and provided a better error messsage
  pkg/interceptors/bitbucket/bitbucket.go
  pkg/interceptors/bitbucket/bitbucket_test.go
  pkg/interceptors/github/github.go
  pkg/interceptors/github/github_test.go
  pkg/interceptors/gitlab/gitlab.go
  pkg/interceptors/gitlab/gitlab_test.go
Labels: approved, lgtm, ok-to-test, release-note, size/M

#1000 Update Release Pipeline and associated Task :technologist: :smiley_cat:
  tekton/README.md
  tekton/account.yaml
  tekton/create-draft-triggers-release.yaml
  tekton/koparse/koparse.py
  tekton/koparse/test_koparse.py
  tekton/koparse/test_release.yaml
  tekton/kustomization.yaml
  tekton/publish.yaml
  tekton/release-cheat-sheet.md
  tekton/release-pipeline.yaml
  tekton/resources.yaml
Labels: approved, lgtm, release-note, size/XXL

#1018 Rewrite the Triggers tutorial for clarity and flow
  docs/getting-started/README.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/L

#1024 Fixes Triggers release pipeline and tasks
  tekton/publish.yaml
Labels: approved, lgtm, release-note, size/S
