Repository tektoncd/triggers, pull requests merged in 2021-08, with the labels that each got.

#1166 Remove Redundant Status Tag from EL Metrics
  docs/eventlisteners.md
  pkg/sink/metrics.go
  pkg/sink/metrics_test.go
Labels: approved, lgtm, release-note, size/S

#1176 Update default branch for getting-started template
  docs/getting-started/triggers.yaml
Labels: approved, kind/bug, lgtm, release-note, size/XS

#1170 Fix status reconcilation for Knative service
  pkg/reconciler/eventlistener/eventlistener.go
Labels: release-note, lgtm, approved, size/S

#1171 Add probes to custom resources(Knative Service)
  pkg/reconciler/eventlistener/eventlistener.go
  pkg/reconciler/eventlistener/eventlistener_test.go
  test/eventlistener_test.go
Labels: release-note, lgtm, approved, size/S

#1182 Add config-defaults configmap to set default values
  cmd/webhook/main.go
  config/config-defaults-triggers.yaml
  config/controller.yaml
  hack/update-codegen.sh
  pkg/apis/config/default.go
  pkg/apis/config/default_test.go
  pkg/apis/config/doc.go
  pkg/apis/config/store.go
  pkg/apis/config/store_test.go
  pkg/apis/config/testdata/config-defaults-empty.yaml
  pkg/apis/config/testdata/config-defaults-triggers.yaml
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/apis/triggers/v1alpha1/event_listener_defaults.go
  pkg/apis/triggers/v1alpha1/event_listener_defaults_test.go
  pkg/apis/triggers/v1beta1/event_listener_defaults.go
  pkg/apis/triggers/v1beta1/event_listener_defaults_test.go
  pkg/reconciler/eventlistener/controller.go
  pkg/reconciler/testing/configmap.go
Labels: release-note, size/XL, lgtm, approved

#1175 Add SetSecuritycontext for EventListener in Controller.yaml
  config/controller.yaml
Labels: release-note, lgtm, size/XS, approved

#1179 Mark webhook and controller as safe-to-evict
  config/controller.yaml
  config/webhook.yaml
Labels: release-note, lgtm, size/XS, approved

#1187 [Cherry-pick v0.15] GJSON version update
  go.mod
  go.sum
  third_party/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/github.com/tidwall/gjson/.travis.yml
  vendor/github.com/tidwall/gjson/README.md
  vendor/github.com/tidwall/gjson/SYNTAX.md
  vendor/github.com/tidwall/gjson/gjson.go
  vendor/github.com/tidwall/gjson/gjson_gae.go
  vendor/github.com/tidwall/gjson/gjson_ngae.go
  vendor/github.com/tidwall/gjson/go.mod
  vendor/github.com/tidwall/gjson/go.sum
  vendor/github.com/tidwall/match/.travis.yml
  vendor/github.com/tidwall/match/README.md
  vendor/github.com/tidwall/match/go.mod
  vendor/github.com/tidwall/match/match.go
  vendor/github.com/tidwall/pretty/README.md
  vendor/github.com/tidwall/pretty/pretty.go
  vendor/modules.txt
Labels: release-note, size/XL, lgtm, approved

#1186 docs: fix formatting of md so list display in HTML
  docs/clusterinterceptors.md
Labels: ok-to-test, lgtm, size/XS, approved, release-note-none

#1190 Fix typo in release cheatsheet
  tekton/release-cheat-sheet.md
Labels: release-note, lgtm, size/XS, approved, kind/misc

#1110 Port FeatureGates to Triggers
  DEVELOPMENT.md
  config/config-feature-flags.yaml
  docs/install.md
  pkg/apis/config/allowed_types.go
  pkg/apis/config/default_test.go
  pkg/apis/config/feature_flags.go
  pkg/apis/config/feature_flags_test.go
  pkg/apis/config/store.go
  pkg/apis/config/store_test.go
  pkg/apis/config/testdata/feature-flags-all-flags-set.yaml
  pkg/apis/config/testdata/feature-flags-empty.yaml
  pkg/apis/config/testdata/feature-flags-invalid-enable-api-fields.yaml
  pkg/apis/config/testdata/feature-flags-triggers.yaml
  pkg/apis/config/testdata/feature-flags-upper-case.yaml
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/apis/triggers/v1alpha1/trigger_template_validation.go
  pkg/apis/triggers/v1beta1/trigger_template_validation.go
  pkg/apis/triggers/v1beta1/version_validation.go
  pkg/apis/triggers/v1beta1/version_validation_test.go
  test/configmap.go
  test/gate.go
Labels: release-note, size/XL, lgtm, approved

#1191 Add Metrics Port to EventListener service
  pkg/reconciler/eventlistener/eventlistener.go
  pkg/reconciler/eventlistener/eventlistener_test.go
Labels: release-note, lgtm, approved, size/S

#1188 Add Status Tag to Event Count Metrics
  docs/eventlisteners.md
  pkg/sink/metrics.go
  pkg/sink/metrics_test.go
  pkg/sink/sink.go
  pkg/sink/validate_payload.go
Labels: release-note, lgtm, approved, size/M

#1192 Fix GitHub EL name in port forward command.
  examples/v1alpha1/github/README.md
Labels: release-note, lgtm, size/XS, approved

#1189 Adds annotation to disable payload validation in eventlistener
  cmd/eventlistenersink/main.go
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1beta1/event_listener_validation.go
  pkg/apis/triggers/v1beta1/event_listener_validation_test.go
  pkg/apis/triggers/validation.go
  pkg/apis/triggers/validation_test.go
  pkg/reconciler/eventlistener/eventlistener.go
  pkg/sink/initialization.go
  pkg/sink/initialization_test.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  pkg/sink/validate_payload.go
  pkg/sink/validate_payload_test.go
  third_party/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
Labels: release-note, lgtm, size/L, approved

#1194 Updates docs for payload validation annotation
  docs/eventlisteners.md
Labels: release-note, lgtm, approved, size/S

#1193 Update readme with proper servicename
  examples/v1alpha1/bitbucket/README.md
  examples/v1alpha1/github/README.md
  examples/v1alpha1/label-selector/README.md
  examples/v1alpha1/namespace-selector/README.md
  examples/v1beta1/bitbucket/README.md
  examples/v1beta1/github/README.md
  examples/v1beta1/label-selector/README.md
  examples/v1beta1/namespace-selector/README.md
Labels: release-note, lgtm, approved, size/S

#1208 Raise the resync period to something more reasonable.
  cmd/eventlistenersink/main.go
Labels: lgtm, size/XS, approved, release-note-none, kind/cleanup

#1211 Patch vendor/ apimachinery to work on 1.22
  hack/patches/patch-vendor-apimachinery-to-work-on-1.22.patch
  hack/update-deps.sh
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
Labels: release-note, lgtm, approved, size/M
