Repository tektoncd/triggers, pull requests merged in 2021-06, with the labels that each got.

#1118 Removes podTemplate field from EventListener
  docs/eventlisteners.md
  pkg/apis/triggers/v1alpha1/event_listener_defaults.go
  pkg/apis/triggers/v1alpha1/event_listener_defaults_test.go
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  third_party/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
Labels: approved, lgtm, release-note, size/L

#1120 Add Clusterrole Aggregate View and Edit for ClusterInterceptor CRD
  config/clusterrole-aggregate-edit.yaml
  config/clusterrole-aggregate-view.yaml
Labels: approved, lgtm, release-note, size/XS

#1123 Add Clusterrole Aggregate View and Edit for ClusterInterceptor CRD
  config/clusterrole-aggregate-edit.yaml
  config/clusterrole-aggregate-view.yaml
Labels: approved, lgtm, release-note, size/XS

#1125 Switch reconciler & sink to using v1beta1 types
  cmd/binding-eval/cmd/root.go
  cmd/eventlistenersink/main.go
  cmd/triggerrun/cmd/root.go
  cmd/triggerrun/cmd/root_test.go
  config/300-clustertriggerbinding.yaml
  config/300-eventlistener.yaml
  config/300-trigger.yaml
  config/300-triggerbinding.yaml
  config/300-triggertemplate.yaml
  pkg/apis/triggers/v1beta1/event_listener_types.go
  pkg/interceptors/bitbucket/bitbucket.go
  pkg/interceptors/bitbucket/bitbucket_test.go
  pkg/interceptors/cel/cel.go
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/cel/triggers.go
  pkg/interceptors/github/github.go
  pkg/interceptors/github/github_test.go
  pkg/interceptors/gitlab/gitlab.go
  pkg/interceptors/gitlab/gitlab_test.go
  pkg/interceptors/interceptors.go
  pkg/interceptors/interceptors_test.go
  pkg/interceptors/interface.go
  pkg/interceptors/server/server.go
  pkg/interceptors/webhook/webhook.go
  pkg/interceptors/webhook/webhook_test.go
  pkg/reconciler/eventlistener/controller.go
  pkg/reconciler/eventlistener/eventlistener.go
  pkg/reconciler/eventlistener/eventlistener_test.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  pkg/sink/validate_payload_test.go
  pkg/template/event.go
  pkg/template/event_test.go
  pkg/template/resource.go
  pkg/template/resource_test.go
  test/controller.go
  test/controller_test.go
  test/params.go
Labels: approved, lgtm, release-note, size/XXL

#1134 Fix the cp command in the release publish task
  tekton/publish.yaml
Labels: approved, lgtm, release-note-none, size/XS

#1129 Add description for compareSecret parameters
  docs/cel_expressions.md
Labels: approved, kind/documentation, lgtm, release-note, size/XS

#1132 Send EL response before Triggers finish processing
  cmd/eventlistenersink/main.go
  cmd/triggerrun/cmd/root.go
  cmd/triggerrun/cmd/root_test.go
  docs/eventlisteners.md
  examples/bitbucket/README.md
  examples/custom-resource/README.md
  examples/eventlistener-tls-connection/README.md
  examples/github/README.md
  examples/gitlab/README.md
  examples/selectors/label/README.md
  examples/selectors/namespace/README.md
  examples/v1alpha1-task/README.md
  pkg/sink/metrics_test.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  test/eventlistener_test.go
Labels: approved, lgtm, release-note, size/L

#1071 Update examples readme to use valid port 8000
  examples/README.md
  examples/bitbucket/README.md
  examples/github/README.md
  examples/gitlab/README.md
  examples/v1alpha1-task/README.md
Labels: approved, lgtm, release-note, size/S
