Repository tektoncd/triggers, pull requests merged in 2021-11, with the labels that each got.

#1260 Fixes broken links and typos in docs
  docs/eventlisteners.md
  docs/install.md
  docs/interceptors.md
  docs/triggerbindings.md
  docs/triggers.md
  docs/triggertemplates.md
  docs/troubleshooting.md
Labels: release-note, lgtm, approved, size/M

#1250 Add e2e test to verify knative examples
  examples/v1alpha1/custom-resource/curl.sh
  examples/v1alpha1/custom-resource/github-knative-listener-customresource.yaml
  examples/v1beta1/custom-resource/curl.sh
  examples/v1beta1/custom-resource/github-knative-listener-customresource.yaml
  test/e2e-tests-examples.sh
Labels: release-note, lgtm, approved, size/M

#1266 Removes v1beta1 AdmissionReview
  config/500-webhooks.yaml
Labels: release-note, lgtm, size/XS, approved

#1275 Focus deployment and service informers on triggers workload
  cmd/controller/main.go
  cmd/triggerrun/cmd/root_test.go
  pkg/interceptors/bitbucket/bitbucket_test.go
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/github/github_test.go
  pkg/interceptors/gitlab/gitlab_test.go
  pkg/interceptors/interceptors_test.go
  pkg/interceptors/server/server_test.go
  pkg/reconciler/eventlistener/controller.go
  pkg/reconciler/eventlistener/eventlistener_test.go
  pkg/sink/sink_test.go
  test/controller.go
  test/controller_test.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/filtered/deployment.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/filtered/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/filtered/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/filtered/service.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/filtered/fake/fake_filtered_factory.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/filtered/filtered_factory.go
  vendor/modules.txt
Labels: release-note, size/XL, lgtm, approved, kind/misc
