Repository tektoncd/triggers, pull requests merged in 2021-01, with the labels that each got.

#884 Update service account name for TLS example
  examples/rbac.yaml
Labels: approved, lgtm, release-note, size/XS

#881 Fix behaviour which allows EL ports to be configured
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, lgtm, ok-to-test, release-note, size/L

#880 Update tekton eventlistener portname owing to istio naming conventions
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
Labels: approved, lgtm, ok-to-test, release-note, size/XS

#885 Update TLS example
  examples/eventlistener-tls-connection/secret.yaml
  examples/eventlistener-tls-connection/tls-eventlistener-interceptor.yaml
  examples/rbac.yaml
Labels: approved, lgtm, release-note, size/S

#887 Add https-listener service port name
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  test/eventlistener_test.go
Labels: approved, lgtm, ok-to-test, release-note, size/L

#891 Use system.DefaultNamespace for interceptor urls
  cmd/interceptors/main.go
  pkg/interceptors/interceptors.go
  pkg/interceptors/interceptors_test.go
  test/eventlistener_test.go
Labels: approved, kind/bug, lgtm, release-note, size/M

#863 Bind admin role so that SA can use PSP
  examples/rbac.yaml
Labels: approved, lgtm, ok-to-test, release-note-none, size/XS

#895 Add core interceptors image to created images
  tekton/publish.yaml
  tekton/release-cheat-sheet.md
  tekton/release-pipeline.yaml
  tekton/resources.yaml
Labels: approved, kind/bug, lgtm, release-note, size/S

#898 Remove the template.Name field
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/trigger_defaults.go
  pkg/apis/triggers/v1alpha1/trigger_defaults_test.go
  pkg/apis/triggers/v1alpha1/trigger_types.go
  pkg/apis/triggers/v1alpha1/trigger_types_convert_test.go
  pkg/apis/triggers/v1alpha1/trigger_validation.go
  pkg/apis/triggers/v1alpha1/trigger_validation_test.go
  pkg/sink/sink_test.go
  pkg/template/resource.go
  pkg/template/resource_test.go
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
  test/eventlistener_scale_test.go
Labels: approved, lgtm, ok-to-test, release-note, size/L

#899 Slightly improve the TriggerTemplate message.
  pkg/resources/create.go
Labels: approved, lgtm, release-note, size/XS

#900 Remove deprecated `spec` style embedded bindings
  examples/eventlisteners/eventlistener-embedded-bindings.yaml
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/trigger_defaults.go
  pkg/apis/triggers/v1alpha1/trigger_defaults_test.go
  pkg/apis/triggers/v1alpha1/trigger_types.go
  pkg/apis/triggers/v1alpha1/trigger_types_convert_test.go
  pkg/apis/triggers/v1alpha1/trigger_validation.go
  pkg/apis/triggers/v1alpha1/trigger_validation_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/template/resource.go
  pkg/template/resource_test.go
  test/builder/eventlistener.go
  test/builder/trigger.go
  test/builder/trigger_test.go
Labels: approved, lgtm, release-note, size/L

#905 Fixed link in EventListener secure connection docs
  docs/eventlisteners.md
Labels: approved, lgtm, ok-to-test, release-note-none, size/XS

#882 Refactor sink test
  pkg/interceptors/bitbucket/bitbucket_test.go
  pkg/interceptors/github/github_test.go
  pkg/sink/sink_test.go
  test/controller.go
  test/raw.go
  test/resources.go
  test/signature.go
  test/signature_test.go
Labels: approved, kind/cleanup, lgtm, release-note, size/XXL

#907 Add links to versioned docs for v0.10.2
  README.md
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#908 Add links to versioned docs for v0.11.0
  README.md
Labels: approved, kind/documentation, lgtm, release-note, size/XS

#913 Revert removal of template.Name field and handle Deprecation of template.Name field
  pkg/apis/triggers/v1alpha1/event_listener_defaults.go
  pkg/apis/triggers/v1alpha1/event_listener_defaults_test.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/trigger_defaults.go
  pkg/apis/triggers/v1alpha1/trigger_defaults_test.go
  pkg/apis/triggers/v1alpha1/trigger_types.go
  pkg/apis/triggers/v1alpha1/trigger_types_convert_test.go
  pkg/apis/triggers/v1alpha1/trigger_validation.go
  pkg/apis/triggers/v1alpha1/trigger_validation_test.go
  pkg/sink/sink_test.go
  pkg/template/resource.go
  pkg/template/resource_test.go
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
  test/eventlistener_scale_test.go
Labels: approved, lgtm, release-note, size/L

#914 Add missing namespace to core-interceptors role
  config/200-role.yaml
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#917 Add missing namespace to core-interceptors role
  config/200-role.yaml
Labels: approved, lgtm, release-note, size/XS

#906 update getting-started tutorial
  docs/getting-started/README.md
  docs/getting-started/pipeline.yaml
  docs/getting-started/rbac/admin-role.yaml
  docs/getting-started/secret.yaml
  docs/getting-started/triggers.yaml
Labels: approved, kind/documentation, lgtm, release-note-none, size/L

#918 Add links to versioned docs for v0.11.1
  README.md
Labels: approved, lgtm, release-note, size/XS

#919 Remove deprecated field template.Name in favour of template.Ref
  pkg/apis/triggers/v1alpha1/event_listener_defaults.go
  pkg/apis/triggers/v1alpha1/event_listener_defaults_test.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/trigger_defaults.go
  pkg/apis/triggers/v1alpha1/trigger_defaults_test.go
  pkg/apis/triggers/v1alpha1/trigger_types.go
  pkg/apis/triggers/v1alpha1/trigger_types_convert_test.go
  pkg/apis/triggers/v1alpha1/trigger_validation.go
  pkg/apis/triggers/v1alpha1/trigger_validation_test.go
  pkg/sink/sink_test.go
  pkg/template/resource.go
  pkg/template/resource_test.go
  test/builder/eventlistener.go
  test/builder/eventlistener_test.go
  test/eventlistener_scale_test.go
Labels: approved, lgtm, release-note, size/L

#922 Update min K8s version for Triggers
  docs/install.md
Labels: approved, lgtm, release-note, size/XS

#927 Send Tekton installation namespace to EL
  pkg/interceptors/interceptors.go
  pkg/interceptors/interceptors_test.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, lgtm, release-note, size/M

#926 Switch to UUID for event IDs
  cmd/triggerrun/cmd/root.go
  go.mod
  go.sum
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  pkg/template/event.go
  pkg/template/event_test.go
  pkg/template/resource.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version4.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/M

#929 [Cherry-Pick] Send Tekton installation namespace to EL
  pkg/interceptors/interceptors.go
  pkg/interceptors/interceptors_test.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, lgtm, release-note, size/M

#930 Add links to versioned docs for v0.11.2
  README.md
Labels: approved, lgtm, release-note, size/XS

#933 Add link to godoc reference
  README.md
Labels: approved, kind/misc, lgtm, release-note, size/XS
