Repository tektoncd/triggers, pull requests merged in 2021-07, with the labels that each got.

#1144 Fix a typo in release-cheatsheet
  tekton/release-cheat-sheet.md
Labels: approved, lgtm, release-note, size/XS

#1148 docs: fix formatting of code examples
  docs/eventlisteners.md
Labels: approved, lgtm, ok-to-test, release-note, size/S

#1151 Update getting started guide with github enterprise config
  docs/getting-started/README.md
  docs/getting-started/webhook-run.yaml
Labels: approved, lgtm, release-note-none, size/XS

#1157 Add links to versioned docs for v0.15.0 & v0.14.2
  README.md
Labels: approved, kind/misc, lgtm, release-note-none, size/XS

#1160 Add Event Count for EventListener Metrics
  docs/eventlisteners.md
  pkg/sink/metrics.go
  pkg/sink/metrics_test.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/metrics/metricstest/resource_metrics.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/XL

#1164 Upate gjson to v1.6.5
  go.mod
  go.sum
  third_party/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/github.com/tidwall/gjson/.travis.yml
  vendor/github.com/tidwall/gjson/README.md
  vendor/github.com/tidwall/gjson/SYNTAX.md
  vendor/github.com/tidwall/gjson/gjson.go
  vendor/github.com/tidwall/gjson/gjson_gae.go
  vendor/github.com/tidwall/gjson/gjson_ngae.go
  vendor/github.com/tidwall/gjson/go.mod
  vendor/github.com/tidwall/gjson/go.sum
  vendor/github.com/tidwall/match/.travis.yml
  vendor/github.com/tidwall/match/README.md
  vendor/github.com/tidwall/match/go.mod
  vendor/github.com/tidwall/match/match.go
  vendor/github.com/tidwall/pretty/README.md
  vendor/github.com/tidwall/pretty/pretty.go
  vendor/modules.txt
Labels: approved, kind/misc, lgtm, release-note, size/XL

#1165 Fix a type error
  examples/README.md
Labels: approved, lgtm, ok-to-test, release-note-none, size/XS

#1163 Update docs for clusterroles packaged for eventlistener
  docs/eventlisteners.md
Labels: approved, lgtm, release-note, size/S

#1167 Update Trigger Flow image and add it to the docs.
  docs/README.md
  images/TriggerFlow.png
  images/TriggerFlow.svg
Labels: approved, lgtm, release-note-none, size/XS
