Repository tektoncd/triggers, pull requests merged in 2021-09, with the labels that each got.

#1212 Add versioned docs links for v0.15.1 and v0.15.2
  README.md
Labels: kind/documentation, release-note, lgtm, size/XS, approved

#1214 Add versioned docs links for v0.16.0
  README.md
  tekton/release-cheat-sheet.md
Labels: release-note, lgtm, size/XS, approved

#1215 Add some documentation on the CEL macros.
  docs/cel_expressions.md
Labels: documentation, kind/documentation, lgtm, approved, size/M, release-note-none

#1216 Fix lint errors and update the linter to revive.
  .golangci.yml
  pkg/reconciler/eventlistener/eventlistener.go
  test/controller.go
Labels: lgtm, size/XS, approved, release-note-none

#1218 Add metadata to our publish task for Tekton Chains to observe & sign
  tekton/publish.yaml
Labels: lgtm, size/XS, approved, release-note-none, kind/misc

#1220 Bump gjson to fix two security vulnerabilities.
  go.mod
  go.sum
  vendor/github.com/tidwall/gjson/README.md
  vendor/github.com/tidwall/gjson/SYNTAX.md
  vendor/github.com/tidwall/gjson/gjson.go
  vendor/github.com/tidwall/gjson/go.mod
  vendor/github.com/tidwall/gjson/go.sum
  vendor/github.com/tidwall/pretty/.travis.yml
  vendor/github.com/tidwall/pretty/README.md
  vendor/github.com/tidwall/pretty/go.mod
  vendor/github.com/tidwall/pretty/pretty.go
  vendor/github.com/tidwall/sjson/.travis.yml
  vendor/github.com/tidwall/sjson/README.md
  vendor/github.com/tidwall/sjson/go.mod
  vendor/github.com/tidwall/sjson/go.sum
  vendor/github.com/tidwall/sjson/sjson.go
  vendor/github.com/tidwall/sjson/sjson_gae.go
  vendor/github.com/tidwall/sjson/sjson_ngae.go
  vendor/modules.txt
Labels: size/XXL, release-note, lgtm, approved

#1225 Fix issue 1219
  pkg/reconciler/eventlistener/eventlistener.go
  pkg/reconciler/eventlistener/eventlistener_test.go
Labels: ok-to-test, lgtm, approved, size/S, release-note-action-required

#1213 eldeployment: remove securityContext.runAsUser
  pkg/reconciler/eventlistener/eventlistener_test.go
  pkg/reconciler/eventlistener/resources/deployment.go
Labels: ok-to-test, lgtm, size/XS, approved, release-note-none

#1230 Add tests for validating that the error we get back is what we expect.
  pkg/apis/triggers/v1beta1/event_listener_validation_test.go
  pkg/apis/triggers/v1beta1/trigger_validation.go
Labels: ok-to-test, release-note, lgtm, size/L, approved
