Repository tektoncd/triggers, pull requests merged in 2021-05, with the labels that each got.

#1068 refactor: move list of allowed ResourceTemplate types to its own package
  pkg/apis/triggers/config/allowed_types.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/trigger_template_types.go
  pkg/apis/triggers/v1alpha1/trigger_template_validation.go
Labels: approved, kind/cleanup, lgtm, release-note, size/M

#1072 Add validation check for triggers
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
Labels: approved, lgtm, release-note, size/M

#1040 Removing deprecated fields
  docs/eventlisteners.md
  examples/README.md
  examples/bitbucket/README.md
  examples/github/README.md
  examples/gitlab/README.md
  examples/selectors/label/README.md
  examples/selectors/namespace/README.md
  examples/v1alpha1-task/README.md
  pkg/apis/triggers/v1alpha1/event_listener_defaults.go
  pkg/apis/triggers/v1alpha1/event_listener_defaults_test.go
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  test/builder/eventlistener.go
Labels: approved, lgtm, release-note, size/L

#1074 Add link between cluster interceptor docs and interceptor docs
  docs/clusterinterceptors.md
Labels: approved, lgtm, release-note-none, size/XS

#1073 Update link to interceptors doc
  docs/README.md
Labels: approved, lgtm, release-note-none, size/XS

#1061 Adding opencensus metrics
  cmd/eventlistenersink/main.go
  docs/eventlisteners.md
  go.mod
  go.sum
  pkg/logging/logging.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  pkg/sink/metrics.go
  pkg/sink/metrics_test.go
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  vendor/go.opencensus.io/.travis.yml
  vendor/go.opencensus.io/go.mod
  vendor/go.opencensus.io/go.sum
  vendor/go.opencensus.io/metric/metricexport/reader.go
  vendor/go.opencensus.io/trace/basetypes.go
  vendor/go.opencensus.io/trace/spanstore.go
  vendor/go.opencensus.io/trace/trace.go
  vendor/go.opencensus.io/trace/trace_api.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/XXL

#1078 Resolving build test issues in PRs
  cmd/interceptors/main.go
  cmd/triggerrun/cmd/root_test.go
  examples/webhook-interceptors/main.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/sink/auth_override.go
  pkg/sink/metrics_test.go
  pkg/sink/sink.go
  pkg/template/jsonpath.go
  pkg/template/jsonpath_test.go
  pkg/template/resource.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/M

#1053 Update roadmap for 2021
  roadmap.md
Labels: approved, kind/misc, lgtm, release-note, size/M

#1080 Migrate from test builders to structs
  pkg/apis/triggers/v1alpha1/cluster_trigger_binding_validation_test.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/trigger_binding_validation_test.go
  pkg/apis/triggers/v1alpha1/trigger_template_validation_test.go
  pkg/apis/triggers/v1alpha1/trigger_validation_test.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  pkg/template/event_test.go
  pkg/template/resource_test.go
Labels: approved, kind/cleanup, lgtm, release-note, size/XXL

#1087 Add EventListener UID to sink response, mark name/namespace as deprecated.
  docs/eventlisteners.md
  pkg/sink/sink.go
  pkg/sink/sink_test.go
  test/eventlistener_test.go
Labels: approved, lgtm, release-note, size/M

#1086 Fix metrics port expose issue for triggers eventlistener
  cmd/eventlistenersink/main.go
  config/controller-service.yaml
  config/controller.yaml
  config/webhook.yaml
  docs/eventlisteners.md
  examples/README.md
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
Labels: approved, lgtm, release-note, size/L

#1093 Fix typo and add versioning for 0.14.0
  README.md
  tekton/release-cheat-sheet.md
Labels: approved, documentation, lgtm, release-note, size/XS

#1096 Migrate reconcilers to unversioned packages
  cmd/controller/main.go
  pkg/reconciler/clusterinterceptor/clusterinterceptor.go
  pkg/reconciler/clusterinterceptor/clusterinterceptor_test.go
  pkg/reconciler/clusterinterceptor/controller.go
  pkg/reconciler/eventlistener/config.go
  pkg/reconciler/eventlistener/controller.go
  pkg/reconciler/eventlistener/eventlistener.go
  pkg/reconciler/eventlistener/eventlistener_test.go
  test/eventlistener_test.go
Labels: approved, kind/cleanup, lgtm, release-note

#1097 Upgrade tektoncd/plumbing version.
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/modules.txt
Labels: approved, lgtm, release-note-none, size/M

#1100 Deprecate podTemplate field
  docs/eventlisteners.md
  pkg/apis/triggers/v1alpha1/event_listener_defaults.go
  pkg/apis/triggers/v1alpha1/event_listener_defaults_test.go
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, release-note, size/L

#1095 Update title fields in docs/README.md
  docs/README.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note-none, size/S

#1104 Upgrade plumbing version.
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/M

#1102 Deprecate podTemplate field
  docs/eventlisteners.md
  pkg/apis/triggers/v1alpha1/event_listener_defaults.go
  pkg/apis/triggers/v1alpha1/event_listener_defaults_test.go
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
Labels: approved, kind/bug, lgtm, release-note, size/L

#1109 Update title fields in docs/README.md (release-v0.14.x patch)
  docs/README.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note-none, size/S

#1107 Adds readiness probe in core-interceptors deployment
  cmd/interceptors/main.go
  config/interceptors/core-interceptors-deployment.yaml
Labels: approved, lgtm, release-note, size/S

#1112 Fix small documentation issue
  docs/interceptors.md
Labels: approved, lgtm, ok-to-test, release-note-none, size/XS

#1108 fix typo for release and interceptors name
  tekton/release-pipeline.yaml
Labels: approved, lgtm, release-note, size/XS

#1106 Fixes namespac in clusterrolebinding in getting-started
  docs/getting-started/README.md
  docs/getting-started/rbac/clusterrolebinding.yaml
  docs/getting-started/rbac/webhook-role.yaml
Labels: approved, lgtm, release-note, size/S

#1113 Removes the replicas field
  docs/eventlisteners.md
  go.sum
  pkg/apis/triggers/v1alpha1/event_listener_defaults.go
  pkg/apis/triggers/v1alpha1/event_listener_defaults_test.go
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  test/builder/eventlistener.go
Labels: approved, lgtm, release-note, size/L

#1114 Add ConfigMap which can contain triggers info
  config/200-role.yaml
  config/201-rolebinding.yaml
  config/config-info.yaml
Labels: approved, kind/feature, lgtm, release-note, size/M

#1116 Fix a broken link in interceptors.md
  docs/interceptors.md
Labels: approved, kind/documentation, lgtm, ok-to-test, release-note-none, size/XS
