Repository tektoncd/triggers, pull requests merged in 2021-04, with the labels that each got.

#1021 Move replicas to KubernetesResource from eventlistener spec
  docs/eventlisteners.md
  examples/eventlisteners/eventlistener-replicas.yaml
  pkg/apis/triggers/v1alpha1/event_listener_defaults.go
  pkg/apis/triggers/v1alpha1/event_listener_defaults_test.go
  pkg/apis/triggers/v1alpha1/event_listener_types.go
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener.go
  pkg/reconciler/v1alpha1/eventlistener/eventlistener_test.go
  test/builder/eventlistener.go
  test/eventlistener_scale_test.go
  test/eventlistener_test.go
Labels: approved, lgtm, release-note, size/L

#1028 Update examples to use both old and new syntax
  docs/eventlisteners.md
Labels: approved, lgtm, release-note, size/L

#1030 resources: Fail on non-string template labels.
  pkg/resources/create.go
  pkg/resources/create_test.go
Labels: approved, kind/bug, lgtm, release-note-none, size/M

#1029 Migrate core interceptors to new format
  pkg/apis/triggers/v1alpha1/event_listener_defaults.go
  pkg/apis/triggers/v1alpha1/trigger_defaults.go
  pkg/apis/triggers/v1alpha1/trigger_defaults_test.go
  pkg/apis/triggers/v1alpha1/trigger_types.go
  pkg/apis/triggers/v1alpha1/trigger_types_test.go
Labels: approved, lgtm, release-note, size/L

#1037 Resolving cache sync issues
  cmd/eventlistenersink/main.go
Labels: approved, lgtm, release-note, size/XS

#1046 Use v1 API for RoleBinding 🦝
  test/ingress/200-ingress-clusterrolebinding.yaml
Labels: approved, lgtm, release-note, size/XS

#1044 Add separate interceptors file result to release pipeline
  tekton/release-cheat-sheet.md
  tekton/release-pipeline.yaml
Labels: approved, lgtm, release-note, size/S

#1039 Resolving file read issue with binding-eval
  cmd/binding-eval/cmd/root.go
Labels: approved, lgtm, release-note-none, size/S

#1050 Capitalization consistency for resourcetemplates
  docs/eventlisteners.md
  docs/triggers.md
  docs/triggertemplates.md
  examples/eventlisteners/cel-eventlistener-interceptor.yaml
  examples/eventlisteners/cel-eventlistener-multiple-overlays.yaml
Labels: approved, lgtm, release-note, size/S

#1035 Add the new `Interceptors` Page
  docs/interceptors.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XL

#1054 Update install documentation
  docs/install.md
Labels: approved, lgtm, ok-to-test, release-note, size/XS

#1048 Rewrite the `ClusterInterceptors` page for clarity and flow
  docs/clusterinterceptors.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/M

#1058 Add links to versioned docs for v0.13.0
  README.md
Labels: approved, lgtm, ok-to-test, release-note, size/XS

#1064 Updating to latest version of plumbing
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/.gitignore
  vendor/github.com/tektoncd/plumbing/CONTRIBUTING.md
  vendor/github.com/tektoncd/plumbing/DEVELOPMENT.md
  vendor/github.com/tektoncd/plumbing/README.md
  vendor/github.com/tektoncd/plumbing/adjustpermissions.py
  vendor/github.com/tektoncd/plumbing/scripts/README.md
  vendor/github.com/tektoncd/plumbing/scripts/deploy-release.sh
  vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, release-note-none, size/L

#1060 Rewrite the `EventListeners` Page
  docs/eventlisteners.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XXL

#1066 Delete obsolete page exposing-eventlisteners.md
  docs/exposing-eventlisteners.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/M

#1049 Provide error for invalid bindings
  pkg/apis/triggers/v1alpha1/trigger_binding_validation.go
  pkg/apis/triggers/v1alpha1/trigger_binding_validation_test.go
Labels: approved, lgtm, release-note, size/M
