Repository tektoncd/triggers, pull requests merged in 2022-10, with the labels that each got.

#1455 Remove unused issue template
  .github/issue-template.md
Labels: lgtm, approved, size/S, release-note-none, kind/misc

#1456 Fix the Typo in Trigger Types API docs
  docs/triggers-api.md
  pkg/apis/triggers/v1alpha1/trigger_types.go
  pkg/apis/triggers/v1beta1/trigger_types.go
Labels: lgtm, size/XS, approved, release-note-none, kind/misc

#1461 Add releases.md
  README.md
  releases.md
  tekton/release-cheat-sheet.md
Labels: kind/documentation, lgtm, size/L, approved, release-note-none

#1458 Add OpenSSF Best Practices Badge
  README.md
Labels: release-note, lgtm, size/XS, approved

#1472 Make the webhook port number configurable
  cmd/webhook/main.go
Labels: ok-to-test, release-note, lgtm, size/XS, approved
