Repository tektoncd/triggers, pull requests merged in 2022-09, with the labels that each got.

#1420 Deprecate Trigger as well as Namespace-Selector in EventListener Spec
  docs/eventlisteners.md
Labels: kind/documentation, release-note, lgtm, size/XS, approved

#1428 Add examples for Bitbucket Cloud and Update doc
  docs/interceptors.md
  examples/v1alpha1/bitbucket-server/README.md
  examples/v1alpha1/bitbucket-server/bitbucket-listener.yaml
  examples/v1alpha1/bitbucket-server/curl.sh
  examples/v1alpha1/bitbucket-server/rbac.yaml
  examples/v1alpha1/bitbucket-server/secret.yaml
  examples/v1alpha1/bitbucket-server/triggerbinding.yaml
  examples/v1alpha1/bitbucket-server/triggertemplate.yaml
  examples/v1beta1/bitbucket-cloud/README.md
  examples/v1beta1/bitbucket-cloud/bitbucket-listener.yaml
  examples/v1beta1/bitbucket-cloud/curl.sh
  examples/v1beta1/bitbucket-cloud/rbac.yaml
  examples/v1beta1/bitbucket-cloud/triggerbinding.yaml
  examples/v1beta1/bitbucket-cloud/triggertemplate.yaml
  examples/v1beta1/bitbucket-server/README.md
  examples/v1beta1/bitbucket-server/bitbucket-listener.yaml
  examples/v1beta1/bitbucket-server/curl.sh
  examples/v1beta1/bitbucket-server/rbac.yaml
  examples/v1beta1/bitbucket-server/secret.yaml
  examples/v1beta1/bitbucket-server/triggerbinding.yaml
  examples/v1beta1/bitbucket-server/triggertemplate.yaml
  test/e2e-tests-examples.sh
Labels: release-note, lgtm, size/L, approved

#1432 Add Nil Check for context in the core interceptors
  pkg/interceptors/bitbucket/bitbucket.go
  pkg/interceptors/cel/cel.go
  pkg/interceptors/github/github.go
  pkg/interceptors/gitlab/gitlab.go
Labels: lgtm, approved, size/S, release-note-none, kind/security

#1440 Add temporary GOPATH script for codegen
  hack/setup-temporary-gopath.sh
  hack/update-codegen.sh
  hack/update-openapigen.sh
Labels: lgtm, approved, size/M, release-note-none, kind/misc

#1385 Add validation and rotation of certificate for clusterinterceptor
  cmd/interceptors/main.go
  pkg/adapter/adapter.go
  pkg/interceptors/server/server.go
  pkg/interceptors/server/server_test.go
Labels: kind/feature, release-note, lgtm, size/L, approved

#1442 Add that CloudEvents require Alpha flag
  docs/eventlisteners.md
Labels: kind/documentation, lgtm, size/XS, approved, release-note-none

#1443 Update ko to v0.12.0
  tekton/publish.yaml
Labels: lgtm, size/XS, approved, release-note-none, kind/misc

#1445 Add v0.21.0 docs link
  README.md
Labels: documentation, kind/documentation, lgtm, size/XS, approved, release-note-none

#1449 Allow trigger eventID to be used as input to TriggerBinding
  cmd/binding-eval/cmd/root.go
  cmd/triggerrun/cmd/root.go
  docs/triggerbindings.md
  pkg/sink/sink.go
  pkg/template/event.go
  pkg/template/event_test.go
Labels: release-note, lgtm, approved, size/M
