Repository tektoncd/triggers, pull requests merged in 2022-07, with the labels that each got.

#1386 Update webhook-run.yaml
  docs/getting-started/webhook-run.yaml
Labels: ok-to-test, release-note, lgtm, size/XS, approved

#1398 Add watching mechanism to watch on caBundle for core interceptor
  cmd/interceptors/main.go
Labels: kind/bug, release-note, lgtm, approved, size/M

#1397 Add watching mechanism to watch on caBundle for core interceptor
  cmd/interceptors/main.go
Labels: kind/bug, release-note, lgtm, approved, size/M

#1401 Setting Debug level for EventListener
  docs/troubleshooting.md
Labels: documentation, kind/documentation, lgtm, approved, size/S, release-note-none
