Repository tektoncd/triggers, pull requests merged in 2022-06, with the labels that each got.

#1367 Fix RBAC for getting started
  docs/getting-started/rbac/admin-role.yaml
Labels: lgtm, approved, size/M, release-note-none

#1381 Remove Condition from getting started pipeline
  docs/getting-started/pipeline.yaml
Labels: kind/documentation, lgtm, approved, size/S, release-note-none

#1382 Remove Condition from getting started pipeline
  docs/getting-started/pipeline.yaml
Labels: release-note, lgtm, approved, size/S

#1383 match svc port
  config/interceptors/core-interceptors.yaml
Labels: release-note, lgtm, size/XS, approved

#1378 Add watching mechanism to eventlistener to wait for clusterInterceptor caBundle
  pkg/adapter/adapter.go
  pkg/adapter/adapter_test.go
Labels: release-note, lgtm, size/L, approved
