Repository tektoncd/triggers, pull requests merged in 2022-04, with the labels that each got.

#1310 add tool for evaluating cel expresssions
  cmd/cel-eval/README.md
  cmd/cel-eval/cmd/root.go
  cmd/cel-eval/cmd/root_test.go
  cmd/cel-eval/main.go
  cmd/cel-eval/testdata/expression.txt
  cmd/cel-eval/testdata/http.txt
  docs/cel_expressions.md
Labels: ok-to-test, release-note, lgtm, size/L, approved

#1342 Fix the documentation for wildcard in NamespaceSelector EL
  docs/eventlisteners.md
Labels: lgtm, size/XS, approved, release-note-none

#1345 Moved the TriggerGroups to stable
  docs/eventlisteners.md
  pkg/apis/triggers/v1beta1/event_listener_validation.go
  pkg/apis/triggers/v1beta1/event_listener_validation_test.go
Labels: kind/feature, release-note, lgtm, approved, size/M

#1347 Redundant struct
  docs/triggers-api.md
  pkg/apis/triggers/v1beta1/event_listener_types.go
  pkg/apis/triggers/v1beta1/openapi_generated.go
  pkg/apis/triggers/v1beta1/zz_generated.deepcopy.go
Labels: lgtm, size/L, approved, release-note-none, kind/cleanup
