Repository tektoncd/triggers, pull requests merged in 2022-08, with the labels that each got.

#1410 Add v0.20.2 docs link
  README.md
Labels: lgtm, size/XS, approved, release-note-none, kind/misc

#1411 Update RBAC link to point to k8s docs
  docs/install.md
Labels: release-note, lgtm, size/XS, approved

#1412 Fix Knative e2e-tests flakiness & update to v1.6.0
  test/e2e-tests-examples.sh
Labels: lgtm, approved, size/S, release-note-none, kind/flake, kind/misc

#1413 Update Install instructions for binding-eval tool
  docs/triggerbindings.md
Labels: kind/documentation, lgtm, size/XS, approved, release-note-none

#1415 Update Cronjob API in Example to v1
  examples/v1alpha1/cron/cronjob.yaml
  examples/v1beta1/cron/cronjob.yaml
Labels: lgtm, size/XS, approved, release-note-none, kind/misc

#1416 Bump golangci-lint to v1.47.2 to support Go 1.18
  Makefile
  cmd/interceptors/main.go
  pkg/adapter/adapter.go
  pkg/apis/triggers/v1alpha1/trigger_template_validation.go
  pkg/apis/triggers/v1beta1/trigger_template_validation.go
  tools/go.mod
  tools/go.sum
Labels: size/XL, lgtm, approved, release-note-none, kind/misc

#1417 Prefer SHA256 in Github interceptor
  pkg/interceptors/bitbucket/bitbucket_test.go
  pkg/interceptors/github/github.go
  pkg/interceptors/github/github_test.go
  pkg/sink/sink_test.go
  test/signature.go
  test/signature_test.go
Labels: release-note, lgtm, approved, size/M

#1418 Fix cannot create ingress for getting-started guide
  docs/getting-started/rbac/webhook-role.yaml
Labels: ok-to-test, lgtm, size/XS, approved, release-note-none

#1419 Add AzureRepo push and pull request examples
  examples/v1beta1/azurerepo/pull/README.md
  examples/v1beta1/azurerepo/pull/azurerepo-pullrequest-listener.yaml
  examples/v1beta1/azurerepo/pull/rbac.yaml
  examples/v1beta1/azurerepo/push/README.md
  examples/v1beta1/azurerepo/push/azurerepo-push-listener.yaml
  examples/v1beta1/azurerepo/push/rbac.yaml
Labels: release-note, lgtm, size/L, approved, kind/misc

#1422 Remove duplicate word
  pkg/sink/validate_payload.go
Labels: release-note, lgtm, size/XS, approved

#1424 Update log keys to match logstream
  config/config-logging.yaml
Labels: release-note, lgtm, size/XS, approved

#1426 Document that examples expect default namespace
  examples/README.md
Labels: kind/documentation, lgtm, approved, size/S, release-note-none

#1425 Fix tkn command in troubleshooting
  docs/troubleshooting.md
Labels: kind/documentation, lgtm, size/XS, approved, release-note-none

#1435 Pass CommitID to knative logging
  cmd/controller/kodata/HEAD
  cmd/controller/kodata/refs
  cmd/eventlistenersink/kodata/HEAD
  cmd/eventlistenersink/kodata/refs
  cmd/interceptors/kodata/HEAD
  cmd/interceptors/kodata/refs
  cmd/webhook/kodata/HEAD
  cmd/webhook/kodata/refs
Labels: kind/bug, lgtm, size/XS, approved, release-note-none

#1436 Update installation document
  docs/install.md
Labels: lgtm, size/L, approved, release-note-none

#1423 Disable stack traces in error logs
  config/config-logging.yaml
Labels: release-note, lgtm, size/XS, approved
