Repository tektoncd/triggers, pull requests merged in 2022-11, with the labels that each got.

#1476 Modify e2e test scripts to support running on kind
  test/e2e-tests-kind-prow.env
  test/e2e-tests.sh
Labels: release-note, lgtm, approved, size/S

#1469 Respond appropriately to CloudEvent requests
  pkg/sink/sink.go
  pkg/sink/sink_test.go
Labels: release-note, lgtm, size/L, approved

#1467 Refactor interceptor main package
  cmd/interceptors/main.go
  pkg/interceptors/server/server.go
  pkg/interceptors/server/server_test.go
Labels: release-note, lgtm, size/L, approved, kind/misc

#1414 Move CloudEvent to Stable
  docs/eventlisteners.md
  pkg/apis/triggers/v1beta1/event_listener_validation.go
  pkg/apis/triggers/v1beta1/event_listener_validation_test.go
Labels: kind/feature, release-note, lgtm, approved, size/S

#1483 Update CEL version to 0.12.5 and modified functions
  go.mod
  go.sum
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/cel/triggers.go
  vendor/github.com/google/cel-go/cel/BUILD.bazel
  vendor/github.com/google/cel-go/cel/decls.go
  vendor/github.com/google/cel-go/cel/env.go
  vendor/github.com/google/cel-go/cel/io.go
  vendor/github.com/google/cel-go/cel/library.go
  vendor/github.com/google/cel-go/cel/macro.go
  vendor/github.com/google/cel-go/cel/options.go
  vendor/github.com/google/cel-go/cel/program.go
  vendor/github.com/google/cel-go/checker/checker.go
  vendor/github.com/google/cel-go/checker/cost.go
  vendor/github.com/google/cel-go/checker/env.go
  vendor/github.com/google/cel-go/checker/printer.go
  vendor/github.com/google/cel-go/checker/types.go
  vendor/github.com/google/cel-go/common/containers/container.go
  vendor/github.com/google/cel-go/common/debug/debug.go
  vendor/github.com/google/cel-go/common/error.go
  vendor/github.com/google/cel-go/common/operators/operators.go
  vendor/github.com/google/cel-go/common/types/pb/equal.go
  vendor/github.com/google/cel-go/common/types/pb/type.go
  vendor/github.com/google/cel-go/common/types/ref/reference.go
  vendor/github.com/google/cel-go/common/types/timestamp.go
  vendor/github.com/google/cel-go/ext/BUILD.bazel
  vendor/github.com/google/cel-go/ext/encoders.go
  vendor/github.com/google/cel-go/ext/guards.go
  vendor/github.com/google/cel-go/ext/strings.go
  vendor/github.com/google/cel-go/interpreter/interpretable.go
  vendor/github.com/google/cel-go/interpreter/planner.go
  vendor/github.com/google/cel-go/interpreter/prune.go
  vendor/github.com/google/cel-go/parser/helper.go
  vendor/github.com/google/cel-go/parser/macro.go
  vendor/github.com/google/cel-go/parser/parser.go
  vendor/github.com/google/cel-go/parser/unparser.go
  vendor/modules.txt
Labels: size/XXL, release-note, lgtm, approved
