Repository tektoncd/triggers, pull requests merged in 2022-05, with the labels that each got.

#1333 Add changes to run clusterinterceptor as HTTPS
  cmd/interceptors/main.go
  config/200-clusterrole.yaml
  config/201-clusterrolebinding.yaml
  config/interceptors/core-interceptors-deployment.yaml
  config/interceptors/interceptor-secrets.yaml
  docs/clusterinterceptors.md
  docs/triggers-api.md
  pkg/adapter/adapter.go
  pkg/apis/triggers/v1alpha1/cluster_interceptor_defaults.go
  pkg/apis/triggers/v1alpha1/cluster_interceptor_defaults_test.go
  pkg/apis/triggers/v1alpha1/cluster_interceptor_types.go
  pkg/apis/triggers/v1alpha1/cluster_interceptor_types_test.go
  pkg/apis/triggers/v1alpha1/zz_generated.deepcopy.go
  pkg/interceptors/interceptors.go
  pkg/interceptors/interceptors_test.go
  pkg/reconciler/clusterinterceptor/clusterinterceptor_test.go
  pkg/sink/initialization.go
  pkg/sink/sink.go
  test/eventlistener_scale_test.go
Labels: kind/feature, release-note, size/XL, lgtm, approved

#1346 Add Example for GKE Autopilot
  examples/v1beta1/eventlisteners/eventlistener-gke-autopilot.yaml
Labels: documentation, kind/documentation, release-note, lgtm, approved, size/M

#1348 Add v1beta1 specific example in e2e-tests
  examples/v1beta1/triggergroups/eventlistener-triggergroup.yaml
  test/e2e-tests-examples.sh
Labels: lgtm, approved, size/S, release-note-none, kind/misc

#1362 Add Multiarch Image in Getting Started
  docs/getting-started/create-webhook.yaml
Labels: lgtm, size/XS, approved, release-note-none, kind/misc

#1365 Add v0.20.0 docs link
  README.md
Labels: lgtm, size/XS, approved, release-note-none, kind/misc

#1366 Fix the link for Triggers Website config
  tekton/release-cheat-sheet.md
Labels: lgtm, size/XS, approved, release-note-none
