Repository tektoncd/triggers, pull requests merged in 2022-02, with the labels that each got.

#1302 Bump knative.dev/pkg vendoring. Use klog/v2
  go.mod
  go.sum
  hack/spec-gen/main.go
  vendor/github.com/go-logr/logr/.golangci.yaml
  vendor/github.com/go-logr/logr/CHANGELOG.md
  vendor/github.com/go-logr/logr/CONTRIBUTING.md
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/klog/v2/klog_file_others.go
  vendor/k8s.io/klog/v2/klog_file_windows.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/main.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/doc.go
  vendor/knative.dev/pkg/test/logging/logging.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/user_info.go
  vendor/modules.txt
Labels: size/XXL, release-note, lgtm, approved

#1298 Generate API reference docs for Triggers
  docs/triggers-api.md
  go.mod
  go.sum
  hack/reference-docs-gen-config.json
  hack/reference-docs-template/members.tpl
  hack/reference-docs-template/pkg.tpl
  hack/reference-docs-template/placeholder.go
  hack/reference-docs-template/type.tpl
  hack/tools.go
  hack/update-codegen.sh
  hack/update-reference-docs.sh
  pkg/apis/doc.go
  third_party/LICENSE
  third_party/vendor/golang.org/x/crypto/LICENSE
  third_party/vendor/golang.org/x/net/LICENSE
  third_party/vendor/golang.org/x/text/LICENSE
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/.gitignore
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/.goreleaser.yml
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/.travis.yml
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/LICENSE
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/README.md
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/example-config.json
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/go.mod
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/go.sum
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/main.go
  vendor/github.com/russross/blackfriday/v2/.gitignore
  vendor/github.com/russross/blackfriday/v2/.travis.yml
  vendor/github.com/russross/blackfriday/v2/LICENSE.txt
  vendor/github.com/russross/blackfriday/v2/README.md
  vendor/github.com/russross/blackfriday/v2/block.go
  vendor/github.com/russross/blackfriday/v2/doc.go
  vendor/github.com/russross/blackfriday/v2/entities.go
  vendor/github.com/russross/blackfriday/v2/esc.go
  vendor/github.com/russross/blackfriday/v2/go.mod
  vendor/github.com/russross/blackfriday/v2/html.go
  vendor/github.com/russross/blackfriday/v2/inline.go
  vendor/github.com/russross/blackfriday/v2/markdown.go
  vendor/github.com/russross/blackfriday/v2/node.go
  vendor/github.com/russross/blackfriday/v2/smartypants.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: size/XXL, kind/documentation, lgtm, approved, release-note-none

#1309 Fix the spelling and incorrect article use
  docs/triggerbindings.md
  examples/README.md
Labels: kind/documentation, release-note, lgtm, size/XS, approved

#1300 Add enable/disable option to set events for EventListener in controller.yaml
  cmd/controller/main.go
  config/controller.yaml
  docs/events.md
  pkg/reconciler/eventlistener/eventlistener_test.go
  pkg/reconciler/eventlistener/resources/config.go
  pkg/reconciler/eventlistener/resources/container.go
  pkg/reconciler/eventlistener/resources/container_test.go
  pkg/reconciler/eventlistener/resources/custom_test.go
  pkg/reconciler/eventlistener/resources/deployment.go
  pkg/reconciler/events/event.go
  pkg/sink/sink.go
Labels: release-note, lgtm, size/L, approved

#1311 Change Images location for Triggers Flow
  docs/README.md
  docs/images/TriggerFlow.svg
Labels: lgtm, size/XS, approved, release-note-none

#1308 Remove Default HTTPClient in favour Custom HTTPClient
  cmd/controller/main.go
  config/controller.yaml
  pkg/adapter/adapter.go
  pkg/reconciler/eventlistener/eventlistener_test.go
  pkg/reconciler/eventlistener/resources/config.go
  pkg/reconciler/eventlistener/resources/container.go
  pkg/reconciler/eventlistener/resources/container_test.go
  pkg/reconciler/eventlistener/resources/custom_test.go
  pkg/sink/initialization.go
Labels: lgtm, size/L, approved, release-note-none, kind/misc

#1305 Add metrics for ClusterInteceptor, CTB, EL, TT and TB count
  docs/metrics.md
  pkg/reconciler/eventlistener/controller.go
  pkg/reconciler/eventlistener/eventlistener.go
  pkg/reconciler/eventlistener/eventlistener_test.go
  pkg/reconciler/metrics/injection.go
  pkg/reconciler/metrics/metrics.go
  pkg/reconciler/metrics/metrics_test.go
  vendor/knative.dev/pkg/metrics/testing/config.go
  vendor/modules.txt
Labels: release-note, size/XL, lgtm, approved

#1313 Add frontmatter to Triggers API docs
  docs/triggers-api.md
  hack/update-reference-docs.sh
Labels: release-note, lgtm, size/XS, approved, kind/misc

#1314 Add docs links for v0.16.1, v0.17.0, v.0.17.1 and v0.18.0
  README.md
Labels: release-note, lgtm, size/XS, approved

#1316 Update events readme with new event type
  docs/events.md
Labels: kind/documentation, release-note, lgtm, approved

#1317 Add validation for cloudevent uri in Sink
  pkg/sink/sink.go
Labels: lgtm, size/XS, approved, release-note-none, kind/misc

#1319 Add v0.19.0 docs link
  README.md
Labels: lgtm, size/XS, approved, release-note-none, kind/misc
