Repository tektoncd/triggers, pull requests merged in 2023-11, with the labels that each got.

#1669 Add Triggers v0.25.2 and v0.24.2 to the release
  releases.md
Labels: lgtm, approved, size/M, release-note-none, kind/misc

#1670 Update ko to go 1.20 in release task
  tekton/publish.yaml
Labels: lgtm, size/XS, approved, release-note-none, kind/security

#1667 Update triggers core interceptor to create secret when necessary
  pkg/interceptors/server/server.go
  pkg/interceptors/server/server_test.go
Labels: lgtm, approved, size/M, release-note-none, kind/misc

#1672 Disable HTTP/2 for webhoook by updating Knative
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: release-note, lgtm, approved, size/S
