Repository tektoncd/triggers, pull requests merged in 2023-02, with the labels that each got.

#1514 Add support for v1 pipeline types and customruns
  pkg/apis/config/allowed_types.go
  pkg/client/dynamic/clientset/tekton/tekton.go
Labels: release-note, lgtm, approved, size/S

#1523 Fix the error message during InterceptorExecution
  pkg/sink/sink.go
Labels: kind/bug, lgtm, size/XS, approved, release-note-none

#1524 Replace cloudevents resource with task from hub
  docs/getting-started/pipeline.yaml
  docs/getting-started/triggers.yaml
Labels: kind/bug, release-note, lgtm, approved, size/S

#1494 Add SecurityContext to Eventlistener containers
  pkg/reconciler/eventlistener/eventlistener_test.go
  pkg/reconciler/eventlistener/resources/container.go
  pkg/reconciler/eventlistener/resources/container_test.go
  pkg/reconciler/eventlistener/resources/custom_test.go
Labels: lgtm, size/L, approved, release-note-action-required

#1521 Change TLS MinVersion to tls.VersionTLS12 in order to make Triggers run on OCP where FIPS enabled
  cmd/interceptors/main.go
  config/interceptors/00-interceptor-secrets.yaml
  pkg/adapter/adapter.go
Labels: kind/bug, release-note, lgtm, size/XS, approved, kind/security

#1511 Add v0.22.x to releases.md
  releases.md
Labels: release-note, lgtm, approved, size/S, kind/misc

#1530 Replace cloudevents resource with task from hub
  docs/getting-started/pipeline.yaml
  docs/getting-started/triggers.yaml
Labels: release-note, lgtm, approved, size/S

#1532 Add v0.22.2 to releases.md
  releases.md
Labels: release-note, lgtm, size/XS, approved

#1531 chore: use http constants to replace numbers
  cmd/triggerrun/cmd/root_test.go
  pkg/interceptors/webhook/webhook_test.go
  pkg/sink/sink_test.go
  test/eventlistener_test.go
Labels: release-note, lgtm, approved, size/S, kind/misc

#1533 Remove git files from KODATA
  cmd/controller/kodata/HEAD
  cmd/controller/kodata/refs
  cmd/eventlistenersink/kodata/HEAD
  cmd/eventlistenersink/kodata/refs
  cmd/interceptors/kodata/HEAD
  cmd/interceptors/kodata/refs
  cmd/webhook/kodata/HEAD
  cmd/webhook/kodata/refs
Labels: lgtm, size/XS, approved, release-note-none, kind/misc
