Repository tektoncd/triggers, pull requests merged in 2023-08, with the labels that each got.

#1631 Added clarification about escaping special character in TB
  docs/triggerbindings.md
Labels: kind/documentation, lgtm, size/XS, approved, release-note-none

#1633 Add probes support in Triggers eventlistener
  config/controller.yaml
  docs/eventlisteners.md
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1beta1/event_listener_validation.go
  pkg/apis/triggers/v1beta1/event_listener_validation_test.go
  pkg/reconciler/eventlistener/resources/deployment.go
  pkg/reconciler/eventlistener/resources/deployment_test.go
Labels: release-note, lgtm, size/L, approved

#1619 Add AWS CodeCommit examples for push request and also README to configure AWS CodeCommit
  examples/v1beta1/awscodecommit/push/README.md
  examples/v1beta1/awscodecommit/push/awscodecommit-push-listener.yaml
  examples/v1beta1/awscodecommit/push/images/confirmed.png
  examples/v1beta1/awscodecommit/push/images/confirmsubscription.png
  examples/v1beta1/awscodecommit/push/images/createsubscription.png
  examples/v1beta1/awscodecommit/push/images/createsubscriptionsuccess.png
  examples/v1beta1/awscodecommit/push/images/createtopic.png
  examples/v1beta1/awscodecommit/push/images/createtrigger.png
  examples/v1beta1/awscodecommit/push/images/createtriggersuccess.png
  examples/v1beta1/awscodecommit/push/images/img.png
  examples/v1beta1/awscodecommit/push/images/requestconfirmation.png
  examples/v1beta1/awscodecommit/push/images/selectrepo.png
  examples/v1beta1/awscodecommit/push/images/sns.png
  examples/v1beta1/awscodecommit/push/rbac.yaml
Labels: lgtm, size/L, approved, release-note-none

#1624 Change Leader Election Config Map for Controllers and Webhook
  config/config-leader-election-controller.yaml
  config/config-leader-election-webhook.yaml
  config/controller.yaml
  config/webhook.yaml
Labels: kind/feature, lgtm, size/L, approved, release-note-none

#1629 Fix SA1019 error by staticcheck due to deprecation
  cmd/triggerrun/cmd/root_test.go
  pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
  pkg/apis/triggers/v1alpha1/trigger_template_validation_test.go
  pkg/apis/triggers/v1alpha1/trigger_validation_test.go
  pkg/apis/triggers/v1beta1/event_listener_validation_test.go
  pkg/apis/triggers/v1beta1/trigger_template_validation_test.go
  pkg/resources/create_test.go
  pkg/sink/metrics_test.go
  pkg/sink/sink_test.go
  pkg/template/resource_test.go
  test/resources.go
Labels: lgtm, size/L, approved, release-note-none, kind/misc

#1632 Fix EL Status URL for kubernetesresource.serviceport
  pkg/reconciler/eventlistener/resources/service.go
  pkg/reconciler/eventlistener/resources/service_test.go
Labels: kind/bug, lgtm, approved, size/S, release-note-none

#1635 Add v0.25.0 to docs
  releases.md
Labels: lgtm, approved, size/S, release-note-none, kind/misc
