Repository tektoncd/triggers, pull requests merged in 2023-04, with the labels that each got.

#1576 Remove comparing serviceaccount in tests
  test/eventlistener_test.go
Labels: release-note, lgtm, size/XS, approved, kind/cleanup

#1585 Move wlynch to emeritus_approvers
  OWNERS
Labels: release-note, lgtm, size/XS, approved, kind/misc

#1584 Add Default Informers setup to Event Listener Sink
  cmd/eventlistenersink/main.go
Labels: ok-to-test, release-note, lgtm, approved, size/S

#1548 Slack interceptor 1542
  Makefile
  config/interceptors/core-interceptors.yaml
  docs/interceptors.md
  docs/triggers-api.md
  examples/v1beta1/slack/README.md
  examples/v1beta1/slack/curl.sh
  examples/v1beta1/slack/rbac.yaml
  examples/v1beta1/slack/slack-eventlistener-interceptor.yaml
  pkg/apis/triggers/v1beta1/openapi_generated.go
  pkg/apis/triggers/v1beta1/trigger_types.go
  pkg/apis/triggers/v1beta1/zz_generated.deepcopy.go
  pkg/interceptors/server/server.go
  pkg/interceptors/slack/slack.go
  pkg/interceptors/slack/slack_test.go
  pkg/sink/sink.go
  test/e2e-tests-examples.sh
  third_party/LICENSE
  third_party/crypto/internal/boring/LICENSE
  third_party/vendor/golang.org/x/crypto/LICENSE
  third_party/vendor/golang.org/x/net/LICENSE
  third_party/vendor/golang.org/x/sys/cpu/LICENSE
  third_party/vendor/golang.org/x/text/LICENSE
Labels: ok-to-test, release-note, size/XL, lgtm, approved
