Repository tektoncd/triggers, pull requests merged in 2023-05, with the labels that each got.

#1540 Add support for Affinity and TopologySpreadConstraints
  docs/eventlisteners.md
  pkg/apis/triggers/v1alpha1/event_listener_validation.go
  pkg/apis/triggers/v1beta1/event_listener_validation.go
  pkg/apis/triggers/v1beta1/event_listener_validation_test.go
  pkg/reconciler/eventlistener/resources/custom.go
  pkg/reconciler/eventlistener/resources/custom_test.go
  pkg/reconciler/eventlistener/resources/deployment.go
  pkg/reconciler/eventlistener/resources/deployment_test.go
Labels: kind/feature, release-note, lgtm, size/L, approved

#1554 Upgrading Go to 1.19
  go.mod
  go.sum
Labels: size/XXL, lgtm, approved, release-note-none, kind/misc

#1588 Move interceptor types to implementation
  docs/triggers-api.md
  pkg/apis/triggers/v1beta1/event_listener_validation_test.go
  pkg/apis/triggers/v1beta1/openapi_generated.go
  pkg/apis/triggers/v1beta1/trigger_types.go
  pkg/apis/triggers/v1beta1/trigger_validation_test.go
  pkg/apis/triggers/v1beta1/zz_generated.deepcopy.go
  pkg/interceptors/bitbucket/bitbucket.go
  pkg/interceptors/bitbucket/bitbucket_test.go
  pkg/interceptors/cel/cel.go
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/github/github.go
  pkg/interceptors/github/github_test.go
  pkg/interceptors/gitlab/gitlab.go
  pkg/interceptors/gitlab/gitlab_test.go
  pkg/interceptors/interceptors_test.go
  pkg/interceptors/slack/slack.go
  pkg/interceptors/slack/slack_test.go
  pkg/sink/sink_test.go
  third_party/github.com/hashicorp/go-retryablehttp/README.md
  third_party/github.com/hashicorp/go-retryablehttp/client.go
  third_party/golang.org/x/exp/maps/LICENSE
Labels: size/XXL, ok-to-test, lgtm, approved, release-note-none
