Repository tektoncd/triggers, pull requests merged in 2023-03, with the labels that each got.

#1541 Update ko image to latest with Go 1.19
  tekton/publish.yaml
Labels: lgtm, size/XS, approved, release-note-none, kind/misc

#1470 Skip webhook validation on delete for v1beta1
  docs/triggers-api.md
  pkg/apis/triggers/v1beta1/cluster_trigger_binding_validation.go
  pkg/apis/triggers/v1beta1/cluster_trigger_binding_validation_test.go
  pkg/apis/triggers/v1beta1/event_listener_validation.go
  pkg/apis/triggers/v1beta1/event_listener_validation_test.go
  pkg/apis/triggers/v1beta1/trigger_binding_validation.go
  pkg/apis/triggers/v1beta1/trigger_binding_validation_test.go
  pkg/apis/triggers/v1beta1/trigger_template_validation.go
  pkg/apis/triggers/v1beta1/trigger_template_validation_test.go
  pkg/apis/triggers/v1beta1/trigger_validation.go
  pkg/apis/triggers/v1beta1/trigger_validation_test.go
Labels: kind/bug, release-note, lgtm, size/L, approved

#1549 Fix Weight and Title in Docs
  docs/triggers-api.md
Labels: kind/documentation, lgtm, size/XS, approved, release-note-none

#1550 [Release-v0.23.x] Fix Weight and Title in Docs
  docs/triggers-api.md
Labels: kind/documentation, lgtm, size/XS, approved, release-note-none

#1544 Add v0.23.0 to releases.md
  releases.md
Labels: lgtm, approved, size/S, release-note-none, kind/misc

#1545 Add the instruction for release attestation
  tekton/release-cheat-sheet.md
Labels: lgtm, approved, size/S, release-note-none, kind/misc

#1546 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: lgtm, approved, size/M, release-note-none, kind/misc

#1551 Fix marshalJSON for lists of objects
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/cel/triggers.go
Labels: kind/bug, release-note, lgtm, approved, size/S

#1556 Upgrade to latest knative.dev/pkg 1.9
  go.mod
  go.sum
  pkg/client/injection/reconciler/triggers/v1alpha1/clusterinterceptor/reconciler.go
  pkg/client/injection/reconciler/triggers/v1alpha1/eventlistener/reconciler.go
  pkg/client/injection/reconciler/triggers/v1alpha1/interceptor/reconciler.go
  pkg/client/injection/reconciler/triggers/v1beta1/eventlistener/reconciler.go
  third_party/github.com/hashicorp/go-retryablehttp/client.go
  third_party/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
  vendor/k8s.io/gengo/examples/set-gen/sets/byte.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int64.go
  vendor/k8s.io/gengo/examples/set-gen/sets/string.go
  vendor/k8s.io/gengo/generator/import_tracker.go
  vendor/k8s.io/gengo/namer/import_tracker.go
  vendor/k8s.io/utils/net/port.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved, release-note-none, kind/misc

#1563 Add SecurityContext to Eventlistener containers under el-security-context flag
  pkg/reconciler/eventlistener/eventlistener_test.go
  pkg/reconciler/eventlistener/resources/container.go
Labels: release-note, lgtm, approved, size/M, kind/cleanup

#1565 [Release v0.23 Cherry Pick] Add SecurityContext to Eventlistener containers under el-security-context flag
  pkg/reconciler/eventlistener/eventlistener_test.go
  pkg/reconciler/eventlistener/resources/container.go
Labels: release-note, lgtm, approved, size/M
