Repository tektoncd/triggers, pull requests merged in 2023-01, with the labels that each got.

#1500 Set default `Interceptor.Kind` for `EventListener` `TriggerGroups`
  pkg/apis/triggers/v1beta1/event_listener_defaults.go
  pkg/apis/triggers/v1beta1/event_listener_defaults_test.go
Labels: kind/bug, release-note, lgtm, approved, size/M

#1504 Fix the lint error given by CI
  cmd/controller/main.go
  pkg/interceptors/cel/triggers.go
  pkg/reconciler/events/event.go
  pkg/template/jsonpath.go
Labels: lgtm, approved, size/S, release-note-none, kind/misc

#1498 Restore v1alpha1.Runs as valid resources
  pkg/apis/config/allowed_types.go
  pkg/apis/triggers/v1beta1/trigger_template_validation_test.go
Labels: release-note, lgtm, approved, size/M
