Repository tektoncd/triggers, pull requests merged in 2023-09, with the labels that each got.

#1636 Add first and last functions.
  docs/cel_expressions.md
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/cel/triggers.go
Labels: kind/feature, release-note, lgtm, size/L, approved

#1643 Remove Pipelineressources from integration test
  test/e2e-common.sh
Labels: lgtm, size/XS, approved, release-note-none, kind/misc

#1641 Fix bitbucket server example when both SSH and HTTPS enabled
  examples/v1beta1/bitbucket-server/triggerbinding.yaml
Labels: kind/bug, lgtm, size/XS, approved, release-note-none
