Repository tektoncd/triggers, pull requests merged in 2024-02, with the labels that each got.

#1686 Add string translation to CEL interceptor.
  docs/cel_expressions.md
  pkg/interceptors/cel/cel_test.go
  pkg/interceptors/cel/triggers.go
Labels: kind/feature, release-note, lgtm, approved, size/M

#1691 Modify the Knative package and Serving version to align with the Kubernetes version for compatibility
  go.mod
  go.sum
  vendor/go.uber.org/atomic/.codecov.yml
  vendor/go.uber.org/atomic/.gitignore
  vendor/go.uber.org/atomic/CHANGELOG.md
  vendor/go.uber.org/atomic/LICENSE.txt
  vendor/go.uber.org/atomic/Makefile
  vendor/go.uber.org/atomic/README.md
  vendor/go.uber.org/atomic/bool.go
  vendor/go.uber.org/atomic/bool_ext.go
  vendor/go.uber.org/atomic/doc.go
  vendor/go.uber.org/atomic/duration.go
  vendor/go.uber.org/atomic/duration_ext.go
  vendor/go.uber.org/atomic/error.go
  vendor/go.uber.org/atomic/error_ext.go
  vendor/go.uber.org/atomic/float32.go
  vendor/go.uber.org/atomic/float32_ext.go
  vendor/go.uber.org/atomic/float64.go
  vendor/go.uber.org/atomic/float64_ext.go
  vendor/go.uber.org/atomic/gen.go
  vendor/go.uber.org/atomic/int32.go
  vendor/go.uber.org/atomic/int64.go
  vendor/go.uber.org/atomic/nocmp.go
  vendor/go.uber.org/atomic/pointer_go118.go
  vendor/go.uber.org/atomic/pointer_go119.go
  vendor/go.uber.org/atomic/string.go
  vendor/go.uber.org/atomic/string_ext.go
  vendor/go.uber.org/atomic/time.go
  vendor/go.uber.org/atomic/time_ext.go
  vendor/go.uber.org/atomic/uint32.go
  vendor/go.uber.org/atomic/uint64.go
  vendor/go.uber.org/atomic/uintptr.go
  vendor/go.uber.org/atomic/unsafe_pointer.go
  vendor/go.uber.org/atomic/value.go
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/auth_types.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/metrics.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/reconciler/testing/hooks.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/pkg/webhook/helper.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/AUTHORS
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved, release-note-none

#1693 Revert "Follow naming conventions for resourceTemplates"
  cmd/triggerrun/testdata/triggertemplate.yaml
  docs/getting-started/triggers.yaml
  docs/triggers-api.md
  docs/triggers.md
  docs/triggertemplates.md
  examples/v1alpha1/bitbucket-server/triggertemplate.yaml
  examples/v1alpha1/custom-resource/github-knative-listener-customresource.yaml
  examples/v1alpha1/embedded-trigger/triggertemplate.yaml
  examples/v1alpha1/eventlistener-tls-connection/tls-eventlistener-interceptor.yaml
  examples/v1alpha1/eventlisteners/cel-eventlistener-interceptor.yaml
  examples/v1alpha1/eventlisteners/cel-eventlistener-multiple-overlays.yaml
  examples/v1alpha1/github/github-eventlistener-interceptor.yaml
  examples/v1alpha1/gitlab/gitlab-push-listener.yaml
  examples/v1alpha1/label-selector/triggers.yaml
  examples/v1alpha1/namespace-selector/03_trigger.yaml
  examples/v1alpha1/namespacedinterceptor/eventlistener.yaml
  examples/v1alpha1/trigger-ref/triggertemplate.yaml
  examples/v1alpha1/triggertemplates/triggertemplate.yaml
  examples/v1beta1/awscodecommit/push/awscodecommit-push-listener.yaml
  examples/v1beta1/azurerepo/pull/azurerepo-pullrequest-listener.yaml
  examples/v1beta1/azurerepo/push/azurerepo-push-listener.yaml
  examples/v1beta1/bitbucket-cloud/triggertemplate.yaml
  examples/v1beta1/bitbucket-server/triggertemplate.yaml
  examples/v1beta1/custom-resource/github-knative-listener-customresource.yaml
  examples/v1beta1/embedded-trigger/triggertemplate.yaml
  examples/v1beta1/eventlistener-tls-connection/tls-eventlistener-interceptor.yaml
  examples/v1beta1/eventlisteners/cel-eventlistener-interceptor.yaml
  examples/v1beta1/eventlisteners/cel-eventlistener-multiple-overlays.yaml
  examples/v1beta1/eventlisteners/eventlistener-gke-autopilot.yaml
  examples/v1beta1/github-add-changed-files-pr/github-eventlistener-interceptor.yaml
  examples/v1beta1/github-add-changed-files-push-cel/github-eventlistener-interceptor.yaml
  examples/v1beta1/github-owners/github-eventlistener-interceptor.yaml
  examples/v1beta1/github/github-eventlistener-interceptor.yaml
  examples/v1beta1/gitlab/gitlab-push-listener.yaml
  examples/v1beta1/label-selector/triggers.yaml
  examples/v1beta1/namespace-selector/03_trigger.yaml
  examples/v1beta1/slack/slack-eventlistener-interceptor.yaml
  examples/v1beta1/trigger-ref/triggertemplate.yaml
  examples/v1beta1/triggergroups/trigger.yaml
  examples/v1beta1/triggertemplates/triggertemplate.yaml
  pkg/apis/triggers/v1alpha1/trigger_template_types.go
  pkg/apis/triggers/v1alpha1/trigger_template_validation.go
  pkg/apis/triggers/v1alpha1/trigger_template_validation_test.go
  pkg/apis/triggers/v1beta1/openapi_generated.go
  pkg/apis/triggers/v1beta1/trigger_template_types.go
  pkg/apis/triggers/v1beta1/trigger_template_validation.go
  pkg/apis/triggers/v1beta1/trigger_template_validation_test.go
Labels: kind/bug, lgtm, size/L, approved, release-note-none
