Repository tektoncd/triggers, pull requests merged in 2024-05, with the labels that each got.

#1724 Fix GolangCI issues causing test failures
  pkg/adapter/adapter.go
  pkg/interceptors/github/github_test.go
  pkg/interceptors/interceptors_test.go
  pkg/interceptors/webhook/webhook_test.go
  pkg/reconciler/clusterinterceptor/controller.go
  pkg/reconciler/eventlistener/controller.go
  pkg/reconciler/interceptor/controller.go
  test/controller.go
  test/gate.go
  test/init_test.go
Labels: lgtm, approved, size/M, release-note-none, kind/misc

#1712 Update golang/x/net to handle CVE GO-2024-2687
  go.mod
  go.sum
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64le.s
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/aliases.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved, release-note-none, kind/security

#1727 Fix API doc by adding TriggerTemplate to Resource Types
  docs/triggers-api.md
  pkg/apis/triggers/v1alpha1/trigger_template_types.go
  pkg/apis/triggers/v1beta1/trigger_template_types.go
Labels: kind/documentation, lgtm, size/L, approved, release-note-none

#1710 Document EventListener behaviour as CloudEvent sink
  docs/eventlisteners.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none

#1725 Fix is-multi-ns flag for triggerGroups
  pkg/reconciler/eventlistener/resources/container.go
  pkg/reconciler/eventlistener/resources/container_test.go
Labels: kind/bug, ok-to-test, release-note, lgtm, size/L, approved

#1615 Pass Content-Type Header to Interceptor
  pkg/interceptors/interceptors.go
  pkg/interceptors/interceptors_test.go
Labels: kind/bug, release-note, lgtm, approved, size/S

#1716 Node port service match kubernetes resource
  pkg/reconciler/eventlistener/eventlistener_test.go
  pkg/reconciler/eventlistener/resources/common_test.go
  pkg/reconciler/eventlistener/resources/service.go
  pkg/reconciler/eventlistener/resources/service_test.go
Labels: kind/feature, release-note, lgtm, approved, size/M

#1728 Add Minimum Kubernetes Version for Triggers
  README.md
Labels: kind/documentation, lgtm, size/XS, approved, release-note-none

#1708 Add LoadBalancerClass support in EventListener
  docs/eventlisteners.md
  docs/triggers-api.md
  examples/v1beta1/eventlisteners/eventlistener-loadbalancerclass.yaml
  pkg/apis/triggers/v1beta1/event_listener_types.go
  pkg/apis/triggers/v1beta1/event_listener_validation.go
  pkg/apis/triggers/v1beta1/event_listener_validation_test.go
  pkg/apis/triggers/v1beta1/openapi_generated.go
  pkg/apis/triggers/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/eventlistener/resources/common_test.go
  pkg/reconciler/eventlistener/resources/service.go
  pkg/reconciler/eventlistener/resources/service_test.go
Labels: kind/feature, ok-to-test, release-note, lgtm, size/L, approved

#1730 Bump CEL to v0.20.1
  cmd/cel-eval/cmd/root.go
  cmd/cel-eval/cmd/root_test.go
  docs/cel_expressions.md
  pkg/interceptors/cel/cel.go
  pkg/interceptors/cel/cel_test.go
Labels: release-note, lgtm, approved, size/M, kind/cleanup

#1731 Update ko to 0.15.1 and Go to go1.22.2 for publish task
  tekton/publish.yaml
Labels: lgtm, size/XS, approved, release-note-none, kind/misc
