Repository tektoncd/triggers, pull requests merged in 2024-03, with the labels that each got.

#1704 Fix typo
  docs/eventlisteners.md
Labels: kind/documentation, lgtm, size/XS, approved, release-note-none

#1698 Add `lowerAscii()` and `upperAscii()` to documentation
  docs/cel_expressions.md
Labels: ok-to-test, kind/documentation, lgtm, approved, size/M, release-note-none

#1699 Remove tekton resource validation
  cmd/eventlistenersink/main.go
  cmd/triggerrun/cmd/root.go
  docs/triggertemplates.md
  examples/v1beta1/create-configmap/README.md
  examples/v1beta1/create-configmap/create-configmap-interceptor.yaml
  examples/v1beta1/create-configmap/curl.sh
  examples/v1beta1/create-configmap/rbac.yaml
  pkg/adapter/adapter.go
  pkg/apis/config/allowed_types.go
  pkg/apis/triggers/v1alpha1/trigger_template_validation.go
  pkg/apis/triggers/v1alpha1/trigger_template_validation_test.go
  pkg/apis/triggers/v1beta1/trigger_template_validation.go
  pkg/apis/triggers/v1beta1/trigger_template_validation_test.go
  pkg/client/dynamic/clientset/clientset.go
  pkg/client/dynamic/clientset/tekton/tekton.go
  pkg/resources/create_test.go
  pkg/sink/auth_override.go
  pkg/sink/sink_test.go
  test/e2e-tests-examples.sh
Labels: kind/feature, release-note, lgtm, size/L, approved

#1709 Move inactive maintainers to emeritus status
  OWNERS
Labels: lgtm, size/XS, approved, release-note-none, kind/misc
