Repository tektoncd/triggers, pull requests merged in 2024-07, with the labels that each got.

#1735 Set readOnlyRootFilesystem as true in Controller and Webhook
  config/controller.yaml
  config/webhook.yaml
Labels: release-note, lgtm, size/XS, approved, kind/security

#1747 Handle validation when value for runAsGroup and runAsUser is empty
  pkg/apis/config/default.go
  pkg/apis/config/default_test.go
  pkg/reconciler/eventlistener/resources/container.go
  pkg/reconciler/eventlistener/resources/container_test.go
  pkg/reconciler/eventlistener/resources/custom.go
  pkg/reconciler/eventlistener/resources/deployment.go
  pkg/reconciler/eventlistener/resources/deployment_test.go
Labels: kind/feature, release-note, lgtm, approved, size/M

#1750 Updated URL's on eventlisteners.md
  docs/eventlisteners.md
Labels: ok-to-test, kind/documentation, lgtm, approved, size/S, release-note-none

#1751 Update version in readme and release file
  README.md
  releases.md
Labels: lgtm, approved, size/S, release-note-none

#1752 issue-1666: EventListener loglevel for interceptor updated to DEBUG
  pkg/sink/sink.go
Labels: lgtm, size/XS, approved, release-note-none
