Repository tektoncd/triggers, pull requests merged in 2024-08, with the labels that each got.

#1742 Add new flag set-read-only-root-filesystem to set readOnlyRootFilesys…
  cmd/controller/main.go
  config/controller.yaml
  pkg/reconciler/eventlistener/eventlistener_test.go
  pkg/reconciler/eventlistener/resources/config.go
  pkg/reconciler/eventlistener/resources/container.go
  pkg/reconciler/eventlistener/resources/container_test.go
  pkg/reconciler/eventlistener/resources/custom_test.go
Labels: kind/feature, ok-to-test, release-note, lgtm, size/L, approved

#1757 Remove duplicate Triggers reference from TriggerGroup section of documentation
  docs/eventlisteners.md
Labels: ok-to-test, kind/documentation, release-note, lgtm, size/XS, approved

#1756 Add runAsUser and runAsGroup under setSecurityContext flag
  pkg/reconciler/eventlistener/eventlistener_test.go
  pkg/reconciler/eventlistener/resources/container.go
Labels: lgtm, approved, size/S, release-note-none, kind/misc

#1740 Update eventlistener podSeurityContext to adhere to restricted pod se…
  config/config-defaults-triggers.yaml
  pkg/apis/config/default.go
  pkg/apis/config/default_test.go
  pkg/apis/config/testdata/config-defaults-empty.yaml
  pkg/apis/config/testdata/config-defaults-triggers-empty-val.yaml
  pkg/apis/config/testdata/config-defaults-triggers.yaml
  pkg/reconciler/eventlistener/eventlistener_test.go
  pkg/reconciler/eventlistener/resources/deployment.go
  pkg/reconciler/eventlistener/resources/deployment_test.go
Labels: kind/feature, ok-to-test, release-note, lgtm, size/L, approved

#1758 Install latest pipeline release in tests
  test/e2e-common.sh
Labels: release-note, lgtm, size/XS, approved
