Repository tektoncd/triggers, pull requests merged in 2025-05, with the labels that each got.

#1828 Add ghcr.io migration banner to README.md.
  README.md
Labels: ok-to-test, kind/documentation, lgtm, size/XS, approved, release-note-none

#1832 Allow users to set custom securityContext in EventListener spec
  docs/eventlisteners.md
  examples/v1beta1/eventlisteners/eventlistener-securitycontext.yaml
  pkg/apis/triggers/v1beta1/event_listener_validation.go
  pkg/apis/triggers/v1beta1/event_listener_validation_test.go
  pkg/reconciler/eventlistener/eventlistener_test.go
  pkg/reconciler/eventlistener/resources/container.go
  pkg/reconciler/eventlistener/resources/container_test.go
  pkg/reconciler/eventlistener/resources/deployment.go
  pkg/reconciler/eventlistener/resources/deployment_test.go
Labels: release-note, lgtm, size/L, approved

#1647 Enable GolangCI Linter used in Pipeline repo
  .golangci.yml
Labels: lgtm, approved, size/M, release-note-none, kind/misc

#1845 Migrate golangci lint to version 2
  .golangci.yml
Labels: lgtm, size/L, approved, release-note-none, kind/misc
